"""foundation

Revision ID: 0001_foundation
Revises:
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_foundation"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_type", sa.String(length=16), nullable=False),
        sa.Column("email_normalized", sa.String(length=320), nullable=False),
        sa.Column("email_display", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("auth_revision", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("account_type IN ('student','teacher')", name="ck_account_type"),
        sa.CheckConstraint("status IN ('active','suspended','deleted')", name="ck_account_status"),
        sa.CheckConstraint("auth_revision > 0", name="ck_account_revision"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email_normalized"),
        sa.UniqueConstraint("id", "account_type", name="uq_account_id_type"),
    )
    op.create_table(
        "auth_session",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("token_digest", sa.LargeBinary(), nullable=False),
        sa.Column("csrf_digest", sa.LargeBinary(), nullable=False),
        sa.Column("auth_revision", sa.BigInteger(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("idle_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("absolute_expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("absolute_expires_at > created_at", name="ck_session_absolute_expiry"),
        sa.CheckConstraint("octet_length(csrf_digest) = 32", name="ck_session_csrf_digest"),
        sa.CheckConstraint("octet_length(token_digest) = 32", name="ck_session_token_digest"),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_digest"),
    )
    op.create_index(
        op.f("ix_auth_session_account_id"), "auth_session", ["account_id"], unique=False
    )
    op.create_table(
        "course",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_account_id", sa.Uuid(), nullable=True),
        sa.Column("origin_kind", sa.String(length=24), nullable=False),
        sa.Column("baseline_code", sa.String(length=32), nullable=True),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("version", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint(
            "(origin_kind = 'platform_default' AND owner_account_id IS NULL "
            "AND baseline_code IS NOT NULL) OR (origin_kind = 'teacher_custom' "
            "AND owner_account_id IS NOT NULL AND baseline_code IS NULL)",
            name="ck_course_owner_origin",
        ),
        sa.CheckConstraint(
            "origin_kind IN ('platform_default','teacher_custom')", name="ck_course_origin"
        ),
        sa.ForeignKeyConstraint(
            ["owner_account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("baseline_code"),
    )
    op.create_table(
        "learning_space",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_account_id", sa.Uuid(), nullable=False),
        sa.Column("origin_local_id", sa.Uuid(), nullable=True),
        sa.Column("kind", sa.String(length=16), server_default="personal", nullable=False),
        sa.Column("version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column(
            "bound_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("kind IN ('personal','teaching')", name="ck_space_kind"),
        sa.CheckConstraint("version > 0", name="ck_space_version"),
        sa.ForeignKeyConstraint(
            ["owner_account_id"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "owner_account_id", name="uq_space_id_owner"),
        sa.UniqueConstraint("origin_local_id"),
    )
    op.create_index(
        op.f("ix_learning_space_owner_account_id"),
        "learning_space",
        ["owner_account_id"],
        unique=False,
    )
    op.create_table(
        "student_profile",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("account_type", sa.String(length=16), server_default="student", nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.CheckConstraint("account_type = 'student'", name="ck_student_type"),
        sa.ForeignKeyConstraint(
            ["account_id", "account_type"],
            ["account.id", "account.account_type"],
            name="fk_student_account_type",
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "teacher_profile",
        sa.Column("account_id", sa.Uuid(), nullable=False),
        sa.Column("account_type", sa.String(length=16), server_default="teacher", nullable=False),
        sa.Column("display_name", sa.String(length=80), nullable=False),
        sa.Column(
            "verification_state", sa.String(length=16), server_default="pending", nullable=False
        ),
        sa.Column("verification_revision", sa.BigInteger(), server_default="1", nullable=False),
        sa.CheckConstraint("account_type = 'teacher'", name="ck_teacher_type"),
        sa.CheckConstraint(
            "verification_state IN ('pending','verified','rejected','suspended')",
            name="ck_teacher_verification",
        ),
        sa.CheckConstraint("verification_revision > 0", name="ck_teacher_revision"),
        sa.ForeignKeyConstraint(
            ["account_id", "account_type"],
            ["account.id", "account.account_type"],
            name="fk_teacher_account_type",
        ),
        sa.PrimaryKeyConstraint("account_id"),
    )
    op.create_table(
        "artifact",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("version", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_revision_id", sa.Uuid(), nullable=True),
        sa.CheckConstraint("version > 0", name="ck_artifact_version"),
        sa.ForeignKeyConstraint(
            ["space_id"],
            ["learning_space.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("space_id", "id", name="uq_artifact_space_id"),
    )
    op.create_index(op.f("ix_artifact_space_id"), "artifact", ["space_id"], unique=False)
    op.create_table(
        "course_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_id", sa.Uuid(), nullable=False),
        sa.Column("version_no", sa.BigInteger(), nullable=False),
        sa.Column("workflow_state", sa.String(length=16), server_default="draft", nullable=False),
        sa.Column("review_state", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column("scope", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "review_state IN ('pending','reviewed','rejected')", name="ck_course_review"
        ),
        sa.CheckConstraint(
            "workflow_state IN ('draft','review','published','withdrawn')",
            name="ck_course_version_workflow",
        ),
        sa.CheckConstraint("octet_length(content_hash) = 32", name="ck_course_content_hash"),
        sa.CheckConstraint("version_no > 0", name="ck_course_version_number"),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["course.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("course_id", "id", name="uq_course_version_id"),
        sa.UniqueConstraint("course_id", "version_no", name="uq_course_version_number"),
    )
    op.create_table(
        "sync_claim",
        sa.Column("claim_id", sa.Uuid(), nullable=False),
        sa.Column("expected_account_id", sa.Uuid(), nullable=False),
        sa.Column("origin_local_space_id", sa.Uuid(), nullable=False),
        sa.Column("server_space_id", sa.Uuid(), nullable=False),
        sa.Column("manifest_hash", sa.LargeBinary(), nullable=False),
        sa.Column("state", sa.String(length=16), server_default="committed", nullable=False),
        sa.Column(
            "committed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("state = 'committed'", name="ck_claim_state"),
        sa.CheckConstraint("octet_length(manifest_hash) = 32", name="ck_claim_manifest_hash"),
        sa.ForeignKeyConstraint(
            ["expected_account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["server_space_id", "expected_account_id"],
            ["learning_space.id", "learning_space.owner_account_id"],
            name="fk_claim_space_owner",
        ),
        sa.PrimaryKeyConstraint("claim_id"),
        sa.UniqueConstraint("origin_local_space_id"),
    )
    op.create_table(
        "artifact_version",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("parent_revision_id", sa.Uuid(), nullable=True),
        sa.Column("content_hash", sa.LargeBinary(), nullable=False),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("author_source", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "author_source IN ('student','teacher','imported_client')", name="ck_artifact_author"
        ),
        sa.CheckConstraint("octet_length(content_hash) = 32", name="ck_artifact_content_hash"),
        sa.ForeignKeyConstraint(
            ["space_id", "artifact_id", "parent_revision_id"],
            ["artifact_version.space_id", "artifact_version.artifact_id", "artifact_version.id"],
            name="fk_revision_parent_scope",
        ),
        sa.ForeignKeyConstraint(
            ["space_id", "artifact_id"],
            ["artifact.space_id", "artifact.id"],
            name="fk_revision_artifact_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("space_id", "artifact_id", "id", name="uq_artifact_revision_scope"),
    )
    op.create_index(
        op.f("ix_artifact_version_space_id"), "artifact_version", ["space_id"], unique=False
    )
    op.create_table(
        "learning_objective",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("course_version_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("necessary_criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_version_id"],
            ["course_version.id"],
        ),
        sa.PrimaryKeyConstraint("id", "course_version_id"),
        sa.UniqueConstraint("course_version_id", "code", name="uq_objective_code"),
    )
    op.create_table(
        "verification_event",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("space_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_id", sa.Uuid(), nullable=False),
        sa.Column("artifact_revision_id", sa.Uuid(), nullable=False),
        sa.Column("objective_id", sa.Uuid(), nullable=False),
        sa.Column("course_version_id", sa.Uuid(), nullable=False),
        sa.Column("standard_version", sa.String(length=100), nullable=False),
        sa.Column("artifact_hash", sa.LargeBinary(), nullable=False),
        sa.Column("provenance", sa.String(length=24), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "provenance IN ('server_tool','human_review','client_reported')",
            name="ck_verification_provenance",
        ),
        sa.CheckConstraint(
            "octet_length(artifact_hash) = 32", name="ck_verification_artifact_hash"
        ),
        sa.ForeignKeyConstraint(
            ["objective_id", "course_version_id"],
            ["learning_objective.id", "learning_objective.course_version_id"],
            name="fk_verification_objective_version",
        ),
        sa.ForeignKeyConstraint(
            ["space_id", "artifact_id", "artifact_revision_id"],
            ["artifact_version.space_id", "artifact_version.artifact_id", "artifact_version.id"],
            name="fk_verification_artifact_scope",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_event_space_id"), "verification_event", ["space_id"], unique=False
    )

    op.create_foreign_key(
        "fk_artifact_current_revision",
        "artifact",
        "artifact_version",
        ["space_id", "id", "current_revision_id"],
        ["space_id", "artifact_id", "id"],
        deferrable=True,
        initially="DEFERRED",
    )

    # Private data deny by default. Runtime role must be NONSUPERUSER/NOBYPASSRLS,
    # separate from migration owner; SET LOCAL context is server-authenticated only.
    own_space = "owner_account_id = nullif(current_setting('vault.account_id', true), '')::uuid"
    own_child = (
        "EXISTS (SELECT 1 FROM learning_space s WHERE s.id = space_id AND " + own_space + ")"
    )
    policies = {
        "learning_space": own_space,
        "artifact": own_child,
        "artifact_version": own_child,
        "verification_event": own_child,
        "sync_claim": (
            "expected_account_id = nullif(current_setting('vault.account_id', true), '')::uuid"
        ),
    }
    for table, predicate in policies.items():
        op.execute(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY")
        op.execute(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY owner_only ON {table} USING ({predicate}) WITH CHECK ({predicate})"
        )

    op.execute("""CREATE FUNCTION vault_append_only() RETURNS trigger LANGUAGE plpgsql AS $$
        BEGIN RAISE EXCEPTION 'immutable version cannot be changed' USING ERRCODE = '23514';
              END $$""")
    for table in ("artifact_version", "verification_event", "sync_claim"):
        op.execute(
            f"CREATE TRIGGER immutable_version BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION vault_append_only()"
        )
    op.execute("""CREATE FUNCTION vault_space_binding_immutable() RETURNS trigger LANGUAGE
              plpgsql AS $$
        BEGIN
          IF NEW.owner_account_id IS DISTINCT FROM OLD.owner_account_id OR
             (OLD.origin_local_id IS NOT NULL AND NEW.origin_local_id IS DISTINCT FROM
              OLD.origin_local_id)
          THEN RAISE EXCEPTION 'space binding cannot be transferred' USING ERRCODE = '23514';
              END IF;
          RETURN NEW;
        END $$""")
    op.execute(
        "CREATE TRIGGER immutable_binding BEFORE UPDATE ON learning_space "
        "FOR EACH ROW EXECUTE FUNCTION vault_space_binding_immutable()"
    )
    op.execute("""CREATE FUNCTION vault_published_content_immutable() RETURNS trigger LANGUAGE
              plpgsql AS $$
        BEGIN
          IF OLD.workflow_state IN ('published','withdrawn') AND
             (NEW.workflow_state NOT IN ('published','withdrawn') OR
              NEW.review_state IS DISTINCT FROM OLD.review_state OR
             (NEW.content_hash IS DISTINCT FROM OLD.content_hash OR
              NEW.scope IS DISTINCT FROM OLD.scope OR NEW.course_id IS DISTINCT FROM
              OLD.course_id OR
              NEW.version_no IS DISTINCT FROM OLD.version_no))
          THEN RAISE EXCEPTION 'published content cannot be changed' USING ERRCODE = '23514';
              END IF;
          RETURN NEW;
        END $$""")
    op.execute(
        "CREATE TRIGGER immutable_published_content BEFORE UPDATE ON course_version "
        "FOR EACH ROW EXECUTE FUNCTION vault_published_content_immutable()"
    )

    op.execute("""CREATE FUNCTION vault_objective_content_immutable()
        RETURNS trigger LANGUAGE plpgsql AS $$
        DECLARE target_id uuid; previous_id uuid; locked_version record;
        BEGIN
          IF TG_OP = 'DELETE' THEN target_id := OLD.course_version_id;
          ELSE target_id := NEW.course_version_id; END IF;
          IF TG_OP = 'UPDATE' THEN previous_id := OLD.course_version_id; END IF;
          FOR locked_version IN SELECT workflow_state FROM course_version
              WHERE id IN (target_id, previous_id) ORDER BY id FOR UPDATE
          LOOP
            IF locked_version.workflow_state IN ('published','withdrawn')
            THEN RAISE EXCEPTION 'published objective cannot be changed'
                 USING ERRCODE = '23514'; END IF;
          END LOOP;
          IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
          RETURN NEW;
        END $$""")
    op.execute(
        "CREATE TRIGGER immutable_objective BEFORE INSERT OR UPDATE OR DELETE "
        "ON learning_objective FOR EACH ROW "
        "EXECUTE FUNCTION vault_objective_content_immutable()"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_artifact_current_revision", "artifact", type_="foreignkey")
    op.drop_index(op.f("ix_verification_event_space_id"), table_name="verification_event")
    op.drop_table("verification_event")
    op.drop_table("learning_objective")
    op.drop_index(op.f("ix_artifact_version_space_id"), table_name="artifact_version")
    op.drop_table("artifact_version")
    op.drop_table("sync_claim")
    op.drop_table("course_version")
    op.drop_index(op.f("ix_artifact_space_id"), table_name="artifact")
    op.drop_table("artifact")
    op.drop_table("teacher_profile")
    op.drop_table("student_profile")
    op.drop_index(op.f("ix_learning_space_owner_account_id"), table_name="learning_space")
    op.drop_table("learning_space")
    op.drop_table("course")
    op.drop_index(op.f("ix_auth_session_account_id"), table_name="auth_session")
    op.drop_table("auth_session")
    op.drop_table("account")
    op.execute("DROP FUNCTION IF EXISTS vault_objective_content_immutable()")
    op.execute("DROP FUNCTION vault_append_only()")
    op.execute("DROP FUNCTION vault_space_binding_immutable()")
    op.execute("DROP FUNCTION vault_published_content_immutable()")
    # ### end Alembic commands ###
