import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'

test('code and prediction survive immediate departure without running; later reflection does not rewrite the run', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/code?activity=learning-notes')
  await page.getByLabel('代码源文件').fill('print(8)')
  await page.getByLabel('运行前预测').fill('会输出 8')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await page.goto('/code?activity=learning-notes')
  await expect(page.getByLabel('代码源文件')).toHaveValue('print(8)')
  await expect(page.getByLabel('运行前预测')).toHaveValue('会输出 8')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toContainText('8', { timeout: 60000 })
  await page.getByLabel('运行后解释与下一步').fill('预测一致，下一次改变输入')
  await expect(page.getByText('草稿已保存到本机。', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('运行后解释与下一步')).toHaveValue('预测一致，下一次改变输入')
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  await page.getByLabel('代码源文件').fill('print(9)')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toContainText('9', { timeout: 60000 })
  await page.getByLabel('运行后解释与下一步').fill('第二版输出 9')
  await expect(page.getByText('草稿已保存到本机。', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /第 1 版/ }).click()
  await expect(page.getByLabel('运行后解释与下一步')).toHaveValue('预测一致，下一次改变输入')
  await page.goto('/local')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出全部本地记录' }).click()
  const data = JSON.parse(await readFile(await (await download).path(), 'utf8'))
  expect(data.codeAttempts.find((row: { result: { stdout: string } }) => row.result.stdout === '8\n').learning.prediction).toBe('会输出 8')
  expect(data.codeAttempts[0].result.mastery_asserted).toBe(false)
  expect(data.codeDrafts[0].reflection).toBe('预测一致，下一次改变输入')
})
