import { expect, test } from '@playwright/test'

test('recursive task preserves call trace, repaired base case and zero-input condition', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS01-M05-O03')
  await expect(page.getByRole('heading', { name: '递归到达基例后怎样返回', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('基例返回 0，每层乘积都是 0。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toContainText('leave=3 result=0', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const editor = page.getByLabel('代码源文件')
  await editor.fill((await editor.inputValue()).replace('if(n==0) return 0;', 'if(n==0) return 1;'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toContainText('leave=3 result=6', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：满足')
  await page.getByRole('link', { name: '新条件：直接到达基例', exact: true }).click()
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('enter=0\nresult=0\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.reload()
  await expect(page.getByRole('heading', { name: '直接到达基例', exact: true })).toBeVisible()
  await expect(page.getByLabel('标准输出')).toHaveText('enter=0\nresult=0\n')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 30')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('有条件需要巩固')
})
