import { expect, test } from '@playwright/test'

test('real child process state is decoded and restored without claiming mastery', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS07-M02-O01')
  await expect(page.getByRole('heading', { name: 'waitpid 状态字需解码退出值', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('父进程回收子进程后得到等待状态字，解码才是退出值七。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('1792\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('print(status)', 'print(os.WEXITSTATUS(status))'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('7\n', { timeout: 60000 })
  await page.reload()
  await expect(page.getByLabel('标准输出')).toHaveText('7\n')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 27')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('部分条件满足')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
})

test('real thread lost update is repaired with a critical section', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS07-M04-O01')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('1\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('if False:', 'if True:'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('2\n', { timeout: 60000 })
})
