import { expect, test } from '@playwright/test'

test('available fixed checks are labelled separately from pending explanation review', async ({ page }) => {
  await page.goto('/learn/CS01-M10-O03')
  await expect(page.getByText('固定条件可核验 · 解释待复核', { exact: true })).toBeVisible()
})

test('atlas defaults show application relations and preserve explicit user filters', async ({ page }) => {
  await page.goto('/atlas?course=CS01&chapter=CS01-M10&goal=CS01-M10-O03')
  await expect(page.getByRole('button', { name: '后续应用', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: '后续应用', exact: true }).click()
  await page.reload()
  await expect(page.getByRole('button', { name: '后续应用', exact: true })).toHaveAttribute('aria-pressed', 'false')
})

test('damaged candidate is rejected without losing the real old file', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS01-M09-O03')
  await expect(page.getByRole('heading', { name: '候选保存失败不能覆盖最后有效记录', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('直接打开旧文件写入会丢失有效记录，拒绝后无法重读。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('rejected\nno-valid-record\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  let code = await source.inputValue()
  code = code.replace('write_text("/box/tmp/record.txt","broken\\n")', 'write_text("/box/tmp/stage.txt","broken\\n")')
    .replace('load_record("/box/tmp/record.txt",&candidate)', 'load_record("/box/tmp/stage.txt",&candidate)')
    .replace('else { puts("committed");}', 'else {if(rename("/box/tmp/stage.txt","/box/tmp/record.txt")!=0) return 1; puts("committed");}')
  await source.fill(code)
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('rejected\nloaded=7 80\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：满足')
  await page.getByRole('link', { name: '新条件：真实写入打开失败', exact: true }).click()
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('write-failed\nloaded=7 80\n', { timeout: 60000 })
  await page.reload()
  await expect(page.getByLabel('标准输出')).toHaveText('write-failed\nloaded=7 80\n')
})

test('regression evidence distinguishes tool exit from failures detected and fixed', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS01-M10-O03')
  await expect(page.getByRole('heading', { name: '修复之后复跑返回值与状态回归', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('cases=4 failures=2\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('record->score=value;if(value<0||value>100)return 0;return 1;', 'if(value<0||value>100)return 0;record->score=value;return 1;'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('cases=4 failures=0\n', { timeout: 60000 })
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 30')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('部分条件满足')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: `../../document/previews/CS01-0.8-${test.info().project.name}.png`, fullPage: true, animations: 'disabled' })
})
