import { expect, test } from '@playwright/test'

test('branch endpoints retain real failure, repair, policy change and graph evidence', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS01-M03-O03')
  await expect(page.getByRole('heading', { name: '选择能揭示条件缺口的反例', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('60 被错误归到最后一段，输出 10。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('10\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  await page.getByLabel('代码源文件').fill('#include <stdio.h>\nint main(void){int minutes=60; int amount; if(minutes<=30)amount=0; else if(minutes<=60)amount=5; else amount=10; printf("%d\\n",amount); return 0;}')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('5\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：满足')
  await page.getByLabel('运行后解释与下一步').fill('端点必须包含；改变规则后需要重新设计阈值测试。')
  await expect(page.getByText('草稿已保存到本机。', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('运行后解释与下一步')).toHaveValue('端点必须包含；改变规则后需要重新设计阈值测试。')
  await page.getByRole('link', { name: '新条件：收费规则改变', exact: true }).click()
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('0\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 30')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('有条件需要巩固')
})

test('loop prefix evidence records zero and negative values and restores the exact task', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS01-M04-O03')
  await expect(page.getByRole('heading', { name: '累计值必须代表已处理的整个前缀', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('覆盖赋值导致第二轮变成 0，累计不正确。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toContainText('sum=1 count=3', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const editor = page.getByLabel('代码源文件')
  await editor.fill((await editor.inputValue()).replace('sum = delta;', 'sum += delta;'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('step=1 sum=-1\nstep=2 sum=-1\nstep=3 sum=0\nsum=0 count=3\n', { timeout: 60000 })
  await page.getByRole('link', { name: '新条件：结束后不再累计', exact: true }).click()
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('step=1 sum=-1\nsum=-1 count=1\n', { timeout: 60000 })
  await page.reload()
  await expect(page.getByRole('heading', { name: '结束后不再累计', exact: true })).toBeVisible()
  await expect(page.getByLabel('标准输出')).toHaveText('step=1 sum=-1\nsum=-1 count=1\n')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
})
