import { expect, test } from '@playwright/test'

test('quantifier negation retains empty-domain work and partial graph evidence', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS05-M02-O02?task=changed-condition')
  await expect(page.getByRole('heading', { name: '空论域边界', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('空域全称为真，否定全称为假；存在否定见证也是假。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('True\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('all(not x for x in values)', 'any(not x for x in values)'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('False\n', { timeout: 60000 })
  await page.reload()
  await expect(page.getByLabel('标准输出')).toHaveText('False\n')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 30')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('部分条件满足')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
})

test('all-even disconnected graph is rejected for an Euler circuit', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS05-M09-O02')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('True\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('print(all(d % 2 == 0 for d in degree.values()))', 'print(seen == vertices and all(d % 2 == 0 for d in degree.values()))'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('False\n', { timeout: 60000 })
})
