import { expect, test } from '@playwright/test'

test('multifile record task repairs constructor and replaces display independently', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS01-M08-O02')
  await expect(page.getByRole('heading', { name: '头文件约定与多文件实现一致', exact: true })).toBeVisible()
  await expect(page.getByLabel('编辑文件').locator('option')).toHaveCount(4)
  await page.getByLabel('运行前预测').fill('构造器丢弃参数，学号变成 1，分数变成 0。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('student=1 score=0\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  await page.getByLabel('编辑文件').selectOption('record.c')
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('result={1,0}', 'result={id,score}'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('student=7 score=80\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：满足')
  await page.getByRole('link', { name: '新条件：只替换显示模块', exact: true }).click()
  await page.getByLabel('编辑文件').selectOption('display.c')
  await source.fill((await source.inputValue()).replace('student=%d score=%d', 'id=%d;score=%d'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('id=7;score=80\n', { timeout: 60000 })
  await page.reload()
  await page.getByLabel('编辑文件').selectOption('display.c')
  await expect(source).toHaveValue(/id=%d;score=%d/)
  await expect(page.getByLabel('标准输出')).toHaveText('id=7;score=80\n')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 30')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('部分条件满足')
})
