import { expect, test } from '@playwright/test'

test('string task repairs termination and preserves exact-fit and empty conditions', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS01-M06-O02')
  await expect(page.getByRole('heading', { name: '内容之外还要留终止符', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('四个位置没有终止符，有界扫描报告 unterminated。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('unterminated\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('int end=0;', "buffer[length]='\\0';\nint end=0;"))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('length=3 text=a b\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：满足')
  await page.getByLabel('运行后解释与下一步').fill('空格属于内容，第四个位置留给终止符；下一步检查空串。')
  await expect(page.getByText('草稿已保存到本机。', { exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('运行后解释与下一步')).toHaveValue('空格属于内容，第四个位置留给终止符；下一步检查空串。')
  await page.getByRole('link', { name: '新条件：空串仍需终止符', exact: true }).click()
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('unterminated\n', { timeout: 60000 })
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 30')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('有条件需要巩固')
})

test('allocation failure is labelled injection and keeps old values recoverable', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS01-M07-O02')
  await expect(page.getByRole('heading', { name: '扩容成功与失败走不同所有权路径', exact: true })).toBeVisible()
  await page.getByRole('link', { name: '新条件：注入失败保留旧块', exact: true }).click()
  await expect(page.getByText('next=NULL 为明确故障注入；报告 retained，打印 2 4，释放原块。', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('discarded\n2 4\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('puts("discarded")', 'puts("retained")'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('retained\n2 4\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：满足')
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('原理解释：待复核')
  await page.reload()
  await expect(page.getByLabel('标准输出')).toHaveText('retained\n2 4\n')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
})
