import { expect, test } from '@playwright/test'

test('Java object repair produces partial goal evidence and restores its exact artifact', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS02-M01-O01')
  await expect(page.getByRole('heading', { name: '两本书不能共用库存字段', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('static 库存由两个对象共享，后构造的值改变两个读取结果。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('2 2\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('static int copies', 'int copies'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('1 2\n', { timeout: 60000 })
  await page.reload()
  await expect(page.getByLabel('标准输出')).toHaveText('1 2\n')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 24')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('部分条件满足')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
})

test('Java resource and file tasks expose different real tool facts', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS02-M05-O03')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('closed=false\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('try {if(n==1)', 'try(r) {if(n==1)'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('closed=true\n', { timeout: 60000 })
  await page.goto('/learn/CS02-M07-O03')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('loaded=7,0\n', { timeout: 60000 })
})
