import { expect, test } from '@playwright/test'

test('real NOT NULL repairs CHECK unknown-value boundary and restores evidence', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS09-M03-O03')
  await expect(page.getByRole('heading', { name: 'CHECK 为未知时不能替代 NOT NULL', exact: true })).toBeVisible()
  await expect(page.getByLabel('运行语言')).toHaveValue('postgres18')
  await page.getByLabel('运行前预测').fill('CHECK 的 NULL 结果不拒绝行，需要 NOT NULL；受限活动不证明全部约束设计。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('1\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('x integer CHECK', 'x integer NOT NULL CHECK'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('0\n', { timeout: 60000 })
  await page.reload()
  await expect(page.getByLabel('标准输出')).toHaveText('0\n')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 30')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('部分条件满足')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
})

test('real dynamic SQL binding treats injected condition as a value', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS09-M09-O02')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('2\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace("EXECUTE 'SELECT count(*) FROM users WHERE name='''||requested||'''' INTO total", "EXECUTE 'SELECT count(*) FROM users WHERE name=$1' INTO total USING requested"))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('0\n', { timeout: 60000 })
})
