import { expect, test } from '@playwright/test'

test('C++ queue recovery preserves its submitted version and partial graph evidence', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS03-M03-O02')
  await expect(page.getByRole('heading', { name: '循环队列在回绕后保持先进先出', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('第三次入队后的 tail 错误回到 1，下一次入队覆盖 20。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('40 30 10 empty=0\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('tail=tail==2?1:tail+1;', 'tail=(tail+1)%3;'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('20 30 40 empty=0\n', { timeout: 60000 })
  await page.reload()
  await expect(page.getByLabel('标准输出')).toHaveText('20 30 40 empty=0\n')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 30')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('部分条件满足')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
})

test('external sorting uses real files and repairs interleaved runs', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS03-M10-O03')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('1 4 2 3 \n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('if(hasX){', 'if(hasX&&(!hasY||x<=y)){'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('1 2 3 4 \n', { timeout: 60000 })
  await page.goto('/learn/CS03-M04-O02?task=changed-condition')
  await expect(page.getByRole('heading', { name: '没有多次失配回退的交替模式', exact: true })).toBeVisible()
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('0 0 1 2 \n', { timeout: 60000 })
})
