import { expect, test } from '@playwright/test'

test('0/1 knapsack repair restores its exact work while proof stays unverified', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS04-M04-O01')
  await expect(page.getByRole('heading', { name: '0/1 背包压缩状态不能重复使用当前物品', exact: true })).toBeVisible()
  await page.getByLabel('运行前预测').fill('容量向前更新读到了本轮状态，重量二的同一件物品被使用两次。')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('6\n', { timeout: 60000 })
  await expect(page.getByRole('region', { name: '任务条件核验' })).toContainText('本次固定条件：未满足')
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('range(weight, capacity + 1)', 'range(capacity, weight - 1, -1)'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('3\n', { timeout: 60000 })
  await page.reload()
  await expect(page.getByLabel('标准输出')).toHaveText('3\n')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 27')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('部分条件满足')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
})

test('negative-edge counterexample and cover feasibility are separate real tasks', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS04-M06-O01')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('1\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('if False:', 'if any(w < 0 for _, _, w in edges):'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('-1\n', { timeout: 60000 })
  await page.goto('/learn/CS04-M08-O03')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('valid=False within_bound=True\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  await source.fill((await source.inputValue()).replace('cover.update([u])', 'cover.update([u, v])'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('valid=True within_bound=True\n', { timeout: 60000 })
})
