import { expect, test } from '@playwright/test'

test('longest lexer match repair preserves evidence and graph scope', async ({ page }) => {
  test.setTimeout(90000)
  await page.goto('/learn/CS11-M02-O03')
  await expect(page.getByLabel('运行语言')).toHaveValue('python313')
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('>\n', { timeout: 60000 })
  await page.getByRole('button', { name: '修改并开始新版本' }).click()
  const source = page.getByLabel('代码源文件')
  await source.fill((await source.inputValue()).replace('matches[0]', 'max(matches,key=len)'))
  await page.getByRole('button', { name: '保存并运行这一版' }).click()
  await expect(page.getByLabel('标准输出')).toHaveText('>=\n', { timeout: 60000 })
  await page.reload()
  await expect(page.getByLabel('标准输出')).toHaveText('>=\n')
  await page.getByRole('link', { name: '回到知识图谱' }).click()
  await expect(page.locator('.scope-total strong')).toContainText('0 / 27')
  await expect(page.locator('.objective-inspector .evidence-pill')).toHaveText('部分条件满足')
  expect(await page.evaluate(() => document.body.scrollWidth <= window.innerWidth)).toBe(true)
})

test('scope shadowing searches inner environment first', async ({ page }) => {
 test.setTimeout(90000)
 await page.goto('/learn/CS11-M06-O02')
 await page.getByRole('button', { name: '保存并运行这一版' }).click()
 await expect(page.getByLabel('标准输出')).toHaveText('1\n', { timeout: 60000 })
 await page.getByRole('button', { name: '修改并开始新版本' }).click()
 const source=page.getByLabel('代码源文件')
 await source.fill((await source.inputValue()).replace('for scope in scopes if','for scope in reversed(scopes) if'))
 await page.getByRole('button', { name: '保存并运行这一版' }).click()
 await expect(page.getByLabel('标准输出')).toHaveText('2\n', { timeout: 60000 })
})
