"""Original finite compiler experiments; custom language rules are explicit."""

from pathlib import Path

from code_authoring import CodeBook

ROOT = Path(__file__).resolve().parents[2]
book = CodeBook(
    ROOT,
    "CS11-core-scope-0.1.0",
    "CS11-core-practice-0.1.0",
    "原创有限编译阶段工件；完整小语言编译器及独立程序集待建设。",
    course="CS11",
    standard="code-fixed-condition-v1",
)
SOURCES = [
    (
        "cc-lexer",
        "Cornell Lexical Analysis",
        "https://www.cs.cornell.edu/courses/cs4120/2026sp/notes/leximpl/",
        "NFA epsilon closure and subset construction",
    ),
    (
        "cc-parser",
        "Cornell Top-down Analysis",
        "https://www.cs.cornell.edu/courses/cs4120/2026sp/notes/topdown/",
        "nullable, FIRST/FOLLOW, table conflicts",
    ),
    (
        "cc-lr",
        "Cornell LR parsing",
        "https://www.cs.cornell.edu/courses/cs4120/2026sp/notes/lr/",
        "item lookahead and conflicts",
    ),
    (
        "cc-semantic",
        "Cornell Semantic Analysis",
        "https://www.cs.cornell.edu/courses/cs4120/2026sp/notes/semantic/",
        "symbol environments and nested scopes",
    ),
    (
        "cc-ast",
        "LLVM Parser and AST",
        "https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/LangImpl02.html",
        "AST and operator precedence; original Python experiments, not LLVM implementation",
    ),
    (
        "cc-dataflow",
        "Cornell Live Variable Analysis",
        "https://www.cs.cornell.edu/courses/cs4120/2023sp/notes/livevar/",
        "use/def and live-in transfer",
    ),
    (
        "cc-teaching-ir",
        "Cornell Intermediate Representations",
        "https://www.cs.cornell.edu/courses/cs4120/2023sp/notes/ir/",
        "machine-independent teaching representation",
    ),
    (
        "cc-ir",
        "LLVM IR Generation",
        "https://llvm.org/docs/tutorial/MyFirstLanguageFrontend/LangImpl03.html",
        "AST lowering context; original teaching IR is not LLVM IR",
    ),
]
book.package["sources"] = [
    {
        "id": k,
        "title": t,
        "url": u,
        "locator": l,
        "checked_at": "2026-10-10",
        "status": "authority_checked",
    }
    for k, t, u, l in SOURCES
]
book.package["activities"] = []


def add(
    module,
    objective,
    title,
    theory,
    source,
    code,
    wrong,
    right,
    before,
    after,
    changed_before,
    changed_after,
    variant,
):
    goal = f"CS11-M{module:02d}-O{objective:02d}"
    initial = "n = int(input())\n" + code.strip() + "\n"
    assert wrong in initial, goal
    repaired = initial.replace(wrong, right)
    cases = []
    for task, label, stdin, first, second in [
        ("base", title, "1\n", before, after),
        ("changed-condition", variant, "2\n", changed_before, changed_after),
    ]:
        request = {
            "language": "python313",
            "entry": "main.py",
            "files": {"main.py": initial},
            "stdin": stdin,
        }
        answer = {**request, "files": {"main.py": repaired}}
        cases.append(
            (
                task,
                label,
                "先写输入约束及预测，运行并保存反例，修改后解释哪些结论尚未证明。",
                request,
                answer,
                first,
                second,
            )
        )
    book.add(
        goal,
        title,
        "标注契约与证据，再用实际运行定位违反条件的步骤。",
        [
            theory,
            "本例的固定运行只支持列出的观察；证明、一般界和独立迁移不由输出代替。",
        ],
        [
            "先区分输出错误、输入前提变化和论证缺口。",
            "检查最小反例与边界，并解释修改依据。",
        ],
        [source],
        cases,
    )


# Each row: module, objective, title, declared rule, source, program, defect,
# correction, base before/after, changed before/after, changed-condition label.
CASES = [
    (
        1,
        1,
        "类型检查应在生成代码前完成",
        "本原创阶段流水线在语义错误时禁止生成指令。",
        "cc-semantic",
        "type_ok=n==2\nstages=['lex','parse','emit']\nprint(' '.join(stages))",
        "stages=['lex','parse','emit']",
        "stages=['lex','parse','type']+(['emit'] if type_ok else [])",
        "lex parse emit\n",
        "lex parse type\n",
        "lex parse emit\n",
        "lex parse type emit\n",
        "类型检查通过",
    ),
    (
        1,
        2,
        "负整数除法按小语言截零规则执行",
        "原创小语言整数除法向零截断，不继承Python地板除法；整数任意精度且除零另报错。",
        "cc-ast",
        "a=-7 if n==1 else 7;b=3\nprint(a//b)",
        "a//b",
        "(1 if a*b>=0 else -1)*(abs(a)//abs(b))",
        "-3\n",
        "-2\n",
        "2\n",
        "2\n",
        "正整数除法",
    ),
    (
        1,
        3,
        "词法错误位置不能被忽略",
        "原创词法字符集仅数字、空白和加号，报告首个非法字符的零起始偏移，不跳过非法字符。",
        "cc-lexer",
        "text='1@2' if n==1 else '1+2'\nbad=next((i for i,c in enumerate(text) if not(c.isdigit() or c in '+ ')),None)\nprint('ok')",
        "print('ok')",
        "print('lex:'+str(bad) if bad is not None else 'ok')",
        "ok\n",
        "lex:1\n",
        "ok\n",
        "ok\n",
        "无非法字符",
    ),
    (
        2,
        1,
        "标识符规则禁止数字开头",
        "原创ASCII标识符首字符为字母或下划线，后续允许数字；fullmatch要求整个输入。",
        "cc-lexer",
        "import re\ntext='2x' if n==1 else 'x2'\nprint(bool(re.fullmatch('[A-Za-z0-9_]+',text)))",
        "'[A-Za-z0-9_]+'",
        "'[A-Za-z_][A-Za-z0-9_]*'",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "数字在后续位置",
    ),
    (
        2,
        2,
        "NFA起始集合须取epsilon闭包",
        "原创NFA：0经epsilon到1，1经a到2，2接受；输入前需计算可达闭包，有限NFA不宣称完整正则转换器。",
        "cc-lexer",
        "eps={0:{1}};states={0} if n==1 else {1}\nfor c in 'a':states={2 for q in states if q==1 and c=='a'}\nprint(2 in states)",
        "for c in 'a':",
        "todo=list(states)\nwhile todo:\n q=todo.pop()\n for r in eps.get(q,set())-states:states.add(r);todo.append(r)\nfor c in 'a':",
        "False\n",
        "True\n",
        "True\n",
        "True\n",
        "从消费状态开始",
    ),
    (
        2,
        3,
        "最长匹配不能按首条规则抢先返回",
        "原创运算符候选>=与>，匹配同一输入时选最长；等长规则优先级另需定义。",
        "cc-lexer",
        "text='>=1' if n==1 else '>1'\nmatches=[op for op in ['>','>='] if text.startswith(op)]\nprint(matches[0])",
        "matches[0]",
        "max(matches,key=len)",
        ">\n",
        ">=\n",
        ">\n",
        ">\n",
        "无前缀冲突",
    ),
    (
        3,
        1,
        "空产生式允许空输入",
        "原创CFG S→aS|epsilon识别a的任意非负重复；非空判断错误排除了epsilon。",
        "cc-parser",
        "word='' if n==1 else 'aa'\nprint(bool(word) and all(c=='a' for c in word))",
        "bool(word) and all(c=='a' for c in word)",
        "all(c=='a' for c in word)",
        "False\n",
        "True\n",
        "True\n",
        "True\n",
        "非空合法串",
    ),
    (
        3,
        2,
        "同串的不同合法树显示二义性",
        "原创E→E+E|E*E|整数，对2+3*4构造两棵合法树；语义不同不代表通用二义性决策算法。",
        "cc-ast",
        "a,b,c=(2,3,4) if n==1 else (1,1,1)\nleft=(a+b)*c;right=a+b*c\nprint(left==right)",
        "print(left==right)",
        "print(str(left)+' '+str(right))",
        "False\n",
        "20 14\n",
        "True\n",
        "2 2\n",
        "不同树偶然同值",
    ),
    (
        3,
        3,
        "减法结合性应由树结构落实",
        "原创整数减法左结合，8-3-1取(8-3)-1；括号改变结合由显式树定义。",
        "cc-ast",
        "a,b,c=(8,3,1) if n==1 else (6,2,0)\nprint(a-(b-c))",
        "a-(b-c)",
        "(a-b)-c",
        "6\n",
        "4\n",
        "4\n",
        "4\n",
        "末项为零",
    ),
    (
        4,
        1,
        "可空前缀要传播后续FIRST",
        "原创S→AB，A→epsilon|a，B→b，FIRST不把epsilon列作终结符；可空标志另存。",
        "cc-parser",
        "nullable=n==1\nfirst_a={'a'};first_b={'b'}\nfirst_s=first_a\nprint(' '.join(sorted(first_s)))",
        "first_s=first_a",
        "first_s=first_a|first_b if nullable else first_a",
        "a\n",
        "a b\n",
        "a\n",
        "a\n",
        "前缀不可空",
    ),
    (
        4,
        2,
        "预测表冲突要保留全部候选",
        "原创预测表候选S→a与S→ab同在a格，不能靠字典覆盖伪称LL1；只检查给定格不构造全文法。",
        "cc-parser",
        "rules=['a','ab'] if n==1 else ['a']\ntable={}\nfor rule in rules:table['a']=rule\nprint(len(table))",
        "for rule in rules:table['a']=rule\nprint(len(table))",
        "for rule in rules:table.setdefault('a',[]).append(rule)\nprint(len(table['a']))",
        "1\n",
        "2\n",
        "1\n",
        "1\n",
        "单一候选",
    ),
    (
        4,
        3,
        "递归下降必须消费完整输入",
        "原创表达式仅一个整数；解析首token成功但残留第二整数应报语法错误。",
        "cc-parser",
        "tokens=['1','2'] if n==1 else ['1']\nindex=0\ndef integer():\n global index\n value=int(tokens[index]);index+=1;return value\nvalue=integer()\nprint(value)",
        "print(value)",
        "print(value if index==len(tokens) else 'syntax:extra')",
        "1\n",
        "syntax:extra\n",
        "1\n",
        "1\n",
        "完整单整数",
    ),
    (
        5,
        1,
        "归约仅弹出产生式右部",
        "原创S→ab，栈含哨兵$，归约弹出两符号后压S，不弹出哨兵。",
        "cc-lr",
        "stack=['$','a','b'] if n==1 else ['x','$','a','b']\ndel stack[-3:];stack.append('S')\nprint(' '.join(stack))",
        "del stack[-3:]",
        "del stack[-2:]",
        "S\n",
        "$ S\n",
        "x S\n",
        "x $ S\n",
        "增加下层栈符号",
    ),
    (
        5,
        2,
        "LR项目闭包需要递归预测",
        "原创Sprime→.S、S→.A、A→.a；项目为(left,right,dot)，只做一轮会漏A。这里是LR0闭包非完整LR1。",
        "cc-lr",
        "rules={'S':('A',),'A':('a',)}\nitems={('P',('S',),0)} if n==1 else {('S',('A',),0)}\nfor left,right,dot in list(items):\n if dot<len(right) and right[dot] in rules:items.add((right[dot],rules[right[dot]],0))\nprint(len(items))",
        "for left,right,dot in list(items):\n if dot<len(right) and right[dot] in rules:items.add((right[dot],rules[right[dot]],0))",
        "todo=list(items)\nwhile todo:\n left,right,dot=todo.pop()\n if dot<len(right) and right[dot] in rules:\n  new=(right[dot],rules[right[dot]],0)\n  if new not in items:items.add(new);todo.append(new)",
        "2\n",
        "3\n",
        "2\n",
        "2\n",
        "少一层预测",
    ),
    (
        5,
        3,
        "分析动作冲突不能任意取第一项",
        "原创给定LR动作格shift/reduce；必须报告冲突并检查文法及lookahead，不以任选动作证明文法正确。",
        "cc-lr",
        "actions=['shift','reduce'] if n==1 else ['reduce']\nprint(actions[0])",
        "actions[0]",
        "'conflict' if len(set(actions))>1 else actions[0]",
        "shift\n",
        "conflict\n",
        "reduce\n",
        "reduce\n",
        "无冲突格",
    ),
    (
        6,
        1,
        "未声明变量不能得到默认零值",
        "原创语言读取未声明变量为静态错误；环境表查询不能静默提供默认值。",
        "cc-semantic",
        "env={'x':7};name='y' if n==1 else 'x'\nprint(env.get(name,0))",
        "env.get(name,0)",
        "env[name] if name in env else 'undeclared:'+name",
        "0\n",
        "undeclared:y\n",
        "7\n",
        "7\n",
        "已声明变量",
    ),
    (
        6,
        2,
        "词法作用域从内层向外查找",
        "原创嵌套块inner x=2遮蔽outer x=1；退出块恢复外层表而非修改其值。",
        "cc-semantic",
        "scopes=[{'x':1},{'x':2}] if n==1 else [{'x':1},{}]\nvalue=next(scope['x'] for scope in scopes if 'x' in scope)\nprint(value)",
        "for scope in scopes if",
        "for scope in reversed(scopes) if",
        "1\n",
        "2\n",
        "1\n",
        "1\n",
        "内层无声明",
    ),
    (
        6,
        3,
        "小语言布尔类型不等于整数",
        "原创类型规则明确bool和int不同，Python isinstance(True,int)不能替代静态类型定义。",
        "cc-semantic",
        "value=True if n==1 else 2\nprint(isinstance(value,int))",
        "isinstance(value,int)",
        "type(value) is int",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "整数操作数",
    ),
    (
        7,
        1,
        "三地址码临时结果不能被覆盖",
        "原创a+b*c先保留乘积再相加；教学IR用Python列表执行，不是LLVM指令。",
        "cc-ir",
        "a,b,c=(2,3,4) if n==1 else (0,1,1)\nt=b*c;t=a+b\nprint(t)",
        "t=b*c;t=a+b",
        "t=b*c;t=a+t",
        "5\n",
        "14\n",
        "1\n",
        "1\n",
        "退化相同结果",
    ),
    (
        7,
        2,
        "条件跳转包含两个控制流后继",
        "原创基本块条件跳转true到1/false到2，CFG须保留两条边；本例无异常边。",
        "cc-ir",
        "conditional=n==1\nsuccessors={1}\nprint(' '.join(map(str,sorted(successors))))",
        "successors={1}",
        "successors={1,2} if conditional else {1}",
        "1\n",
        "1 2\n",
        "1\n",
        "1\n",
        "无条件跳转",
    ),
    (
        7,
        3,
        "短路降低不能提前执行右操作数",
        "原创and从左至右短路，false左值不执行有可观察副作用的rhs。",
        "cc-ast",
        "calls=[]\ndef rhs():calls.append('rhs');return True\nleft=n==2\nright=rhs();result=left and right\nprint(len(calls))",
        "right=rhs();result=left and right",
        "result=left and rhs()",
        "1\n",
        "0\n",
        "1\n",
        "1\n",
        "左条件为真",
    ),
    (
        8,
        1,
        "分支合流只保留共同常量",
        "原创分支x=1/x=2的合流不能取左值；两边一致才是已知常量。",
        "cc-ir",
        "left={'x':1};right={'x':2 if n==1 else 1}\nmerged=dict(left)\nprint(merged.get('x','unknown'))",
        "merged=dict(left)",
        "merged={k:v for k,v in left.items() if right.get(k)==v}",
        "1\n",
        "unknown\n",
        "1\n",
        "1\n",
        "分支常量一致",
    ),
    (
        8,
        2,
        "活跃变量需要扣除定义并加入使用",
        "原创单块use={y},def={x},out={x,z}，live_in=use并(out减def)。只是一个传递步骤，非CFG固定点解。",
        "cc-dataflow",
        "use={'y'};defs={'x'};out={'x','z'} if n==1 else {'z'}\nlive=use|out\nprint(' '.join(sorted(live)))",
        "live=use|out",
        "live=use|(out-defs)",
        "x y z\n",
        "y z\n",
        "y z\n",
        "y z\n",
        "后继不使用定义变量",
    ),
    (
        8,
        3,
        "相乘零优化不能删除副作用",
        "原创表达式rhs()*0，rhs写轨迹；简化为常量0仍必须保存调用，有限轨迹非所有优化证明。",
        "cc-ast",
        "calls=[]\ndef rhs():\n if n==1:calls.append('effect')\n return 7\nresult=0\nprint(len(calls),result)",
        "result=0",
        "rhs();result=0",
        "0 0\n",
        "1 0\n",
        "0 0\n",
        "0 0\n",
        "纯函数变体",
    ),
    (
        9,
        1,
        "同时活跃的临时量不能共用存储",
        "原创t1=2、t2=3同时参与求和，两者槽位相同覆盖旧值；不宣称完成全图寄存器分配。",
        "cc-ir",
        "slots={};a=0;b=0 if n==1 else 1\nslots[a]=2;slots[b]=3\nprint(slots[a]+slots[b])",
        "b=0 if n==1 else 1",
        "b=1",
        "6\n",
        "5\n",
        "5\n",
        "5\n",
        "原分配无冲突",
    ),
    (
        9,
        2,
        "栈机减法区分弹出操作数顺序",
        "原创ISA PUSH整数、SUB，弹出先right后left，结果left-right；教学机非物理CPU。",
        "cc-ir",
        "stack=[8,3] if n==1 else [2,2]\nright=stack.pop();left=stack.pop();stack.append(right-left)\nprint(stack[-1])",
        "right-left",
        "left-right",
        "-5\n",
        "5\n",
        "0\n",
        "0\n",
        "相等操作数",
    ),
    (
        9,
        3,
        "端到端比较需观察结果而非仅编译成功",
        "原创表达式(8-3)-1降低后误用右结合栈序；比较参考左结合与编译指令执行，不把能生成代码当正确。",
        "cc-ast",
        "a,b,c=(8,3,1) if n==1 else (4,2,0)\nreference=(a-b)-c\nstack=[a,b,c];right=stack.pop();left=stack.pop();stack.append(left-right);right=stack.pop();left=stack.pop();stack.append(left-right)\nprint('compiled')",
        "print('compiled')",
        "stack=[a,b];right=stack.pop();left=stack.pop();stack.append(left-right);stack.append(c);right=stack.pop();left=stack.pop();stack.append(left-right)\nprint(reference==stack[-1])",
        "compiled\n",
        "True\n",
        "compiled\n",
        "True\n",
        "有限一致输入",
    ),
]
for row in CASES:
    add(*row)
if __name__ == "__main__":
    book.package["relations"] = []
    for module in range(1, 10):
        for left, right in [(1, 2), (2, 3)]:
            book.package["relations"].append(
                dict(
                    **{
                        "from": f"CS11-M{module:02d}-O{left:02d}",
                        "to": f"CS11-M{module:02d}-O{right:02d}",
                    },
                    kind="conceptual_association",
                    reason="同阶段工件对照："
                    + CASES[(module - 1) * 3 + left - 1][2]
                    + "与"
                    + CASES[(module - 1) * 3 + right - 1][2],
                    source_locator=CASES[(module - 1) * 3 + right - 1][4],
                    course_version_id=book.version,
                    review_state="authority_checked",
                    source="原创阶段工件关系，非按教学顺序自动生成严格先修；机制参见公开来源，专业审校不可用。",
                )
            )
    book.save("CS11-core")
