"""Original standard-library ML experiments on declared synthetic data."""

from pathlib import Path

from code_authoring import CodeBook

ROOT = Path(__file__).resolve().parents[2]
book = CodeBook(
    ROOT,
    "CS13-core-scope-0.1.0",
    "CS13-core-practice-0.1.0",
    "原创合成数据与Python标准库训练/计算实验；完整数据项目、独立测试与开放评审待建设。",
    course="CS13",
    standard="code-fixed-condition-v1",
)
SOURCES = [
    (
        "ml-validation",
        "scikit-learn Cross-validation",
        "https://scikit-learn.org/stable/modules/cross_validation.html",
        "model selection and holdout separation",
    ),
    (
        "ml-pca",
        "scikit-learn Decomposition",
        "https://scikit-learn.org/stable/modules/decomposition.html",
        "centered projection and principal components",
    ),
    (
        "ml-backprop",
        "D2L Backpropagation",
        "https://d2l.ai/chapter_multilayer-perceptrons/backprop.html",
        "chain rule and gradient propagation",
    ),
    (
        "ml-math",
        "Python3.13 math",
        "https://docs.python.org/3.13/library/math.html",
        "exp overflow and floating point behavior",
    ),
    (
        "ml-leak",
        "scikit-learn Common Pitfalls",
        "https://scikit-learn.org/stable/common_pitfalls.html",
        "split before fitting; consistent transforms; original implementation does not call sklearn",
    ),
    (
        "ml-metric",
        "scikit-learn Metrics",
        "https://scikit-learn.org/stable/modules/model_evaluation.html",
        "classification and regression metric definitions",
    ),
    (
        "ml-linear",
        "scikit-learn Linear Models",
        "https://scikit-learn.org/stable/modules/linear_model.html",
        "linear/logistic models and regularization",
    ),
    (
        "ml-tree",
        "scikit-learn Trees",
        "https://scikit-learn.org/stable/modules/tree.html",
        "classification impurity and complexity",
    ),
    (
        "ml-ensemble",
        "scikit-learn Ensembles",
        "https://scikit-learn.org/stable/modules/ensemble.html",
        "bagging and boosting distinctions",
    ),
    (
        "ml-neighbor",
        "scikit-learn Neighbors",
        "https://scikit-learn.org/stable/modules/neighbors.html",
        "nearest neighbors and distance",
    ),
    (
        "ml-cluster",
        "scikit-learn Clustering",
        "https://scikit-learn.org/stable/modules/clustering.html",
        "centroids and label-independent evaluation",
    ),
    (
        "ml-save",
        "scikit-learn Persistence",
        "https://scikit-learn.org/stable/model_persistence.html",
        "persisted model dependencies and unsafe loading boundaries",
    ),
]
book.package["sources"] = [
    {
        "id": k,
        "title": t,
        "url": u,
        "locator": l,
        "checked_at": "2026-10-10",
        "status": "authority_checked",
    }
    for k, t, u, l in SOURCES
]
book.package["activities"] = []


def add(
    module,
    objective,
    title,
    theory,
    source,
    code,
    wrong,
    right,
    before,
    after,
    changed_before,
    changed_after,
    variant,
):
    goal = f"CS13-M{module:02d}-O{objective:02d}"
    initial = "n = int(input())\n" + code.strip() + "\n"
    assert wrong in initial, goal
    repaired = initial.replace(wrong, right)
    cases = []
    for task, label, stdin, first, second in [
        ("base", title, "1\n", before, after),
        ("changed-condition", variant, "2\n", changed_before, changed_after),
    ]:
        request = {
            "language": "python313",
            "entry": "main.py",
            "files": {"main.py": initial},
            "stdin": stdin,
        }
        answer = {**request, "files": {"main.py": repaired}}
        cases.append(
            (
                task,
                label,
                "先写输入约束及预测，运行并保存反例，修改后解释哪些结论尚未证明。",
                request,
                answer,
                first,
                second,
            )
        )
    book.add(
        goal,
        title,
        "标注契约与证据，再用实际运行定位违反条件的步骤。",
        [
            theory,
            "本例的固定运行只支持列出的观察；证明、一般界和独立迁移不由输出代替。",
        ],
        [
            "先区分输出错误、输入前提变化和论证缺口。",
            "检查最小反例与边界，并解释修改依据。",
        ],
        [source],
        cases,
    )


CASES = [
    (
        1,
        1,
        "分类标签不能因为整数编码变成回归",
        "原创目标schema明确kind=category，数字是类别编码；任务类型按目标含义声明。",
        "ml-metric",
        "target={'kind':'category' if n==1 else 'continuous','value':1}\nprint('regression')",
        "print('regression')",
        "print('classification' if target['kind']=='category' else 'regression')",
        "regression\n",
        "classification\n",
        "regression\n",
        "regression\n",
        "连续目标",
    ),
    (
        1,
        2,
        "训练特征不得使用预测时不可用的标签",
        "原创记录有prediction_time与label_arrival，预测后的字段不能进入模型输入；标签记录本身仍可用于离线评估。",
        "ml-leak",
        "features={'sensor':1,'future_label':1};arrival={'sensor':0,'future_label':2 if n==1 else 0};prediction_time=1\nprint(' '.join(sorted(features)))",
        "sorted(features)",
        "sorted(k for k in features if arrival[k]<=prediction_time)",
        "future_label sensor\n",
        "sensor\n",
        "future_label sensor\n",
        "future_label sensor\n",
        "所有字段已在预测前出现",
    ),
    (
        1,
        3,
        "多数类基线需报告少数类召回",
        "原创标签9个0一个1，恒猜0准确率高但正类召回为0；基线不是可靠分类器。",
        "ml-metric",
        "truth=[0]*9+[1] if n==1 else [0,1];pred=[0]*len(truth)\nprint(sum(a==b for a,b in zip(truth,pred)))",
        "print(sum(a==b for a,b in zip(truth,pred)))",
        "tp=sum(a==b==1 for a,b in zip(truth,pred));positive=sum(a==1 for a in truth);print(tp,positive)",
        "9\n",
        "0 1\n",
        "1\n",
        "0 1\n",
        "平衡标签集",
    ),
    (
        2,
        1,
        "同一实体不能跨训练与测试泄漏",
        "原创实体id集合，重复实体跨集合时拒绝；只检查实体隔离，不证明时序与所有泄漏路径。",
        "ml-leak",
        "train={'u1','u2'};test={'u2'} if n==1 else {'u3'}\nprint(len(train)>0 and len(test)>0)",
        "len(train)>0 and len(test)>0",
        "not bool(train&test)",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "实体完全隔离",
    ),
    (
        2,
        2,
        "缺失填补参数只能从训练集拟合",
        "原创训练值2/4，测试100不可改变填补均值；参数拟合范围与transform分开。",
        "ml-leak",
        "from fractions import Fraction\ntrain=[2,4];test=[100] if n==1 else [3]\nmean=Fraction(sum(train+test),len(train+test))\nprint(mean)",
        "Fraction(sum(train+test),len(train+test))",
        "Fraction(sum(train),len(train))",
        "106/3\n",
        "3\n",
        "3\n",
        "3\n",
        "测试值等于训练均值",
    ),
    (
        2,
        3,
        "测试数据转换不能重新拟合参数",
        "原创标准化简化为中心化：训练均值3，测试值100/102须减3，不减测试均值。",
        "ml-leak",
        "train=[2,4];test=[100,102] if n==1 else [2,4]\nmean=sum(test)/len(test)\nprint(' '.join(str(int(x-mean)) for x in test))",
        "mean=sum(test)/len(test)",
        "mean=sum(train)/len(train)",
        "-1 1\n",
        "97 99\n",
        "-1 1\n",
        "-1 1\n",
        "两组均值偶然相同",
    ),
    (
        3,
        1,
        "逻辑回归输出须经sigmoid",
        "原创标量logit=0/2，sigmoid用于概率，不把线性得分直接当概率。",
        "ml-linear",
        "import math\nz=0 if n==1 else 2\np=z\nprint(0<p<1)",
        "p=z",
        "p=1/(1+math.exp(-z))",
        "False\n",
        "True\n",
        "False\n",
        "True\n",
        "正logit",
    ),
    (
        3,
        2,
        "平方损失梯度必须乘输入",
        "原创L=(w*x-y)^2/2，dL/dw=(w*x-y)*x；有限解析与数值差分对照另需扩展。",
        "ml-linear",
        "w=1;x=2 if n==1 else 1;y=0\ngrad=w*x-y\nprint(grad)",
        "grad=w*x-y",
        "grad=(w*x-y)*x",
        "2\n",
        "4\n",
        "1\n",
        "1\n",
        "单位输入",
    ),
    (
        3,
        3,
        "L2项不可写成参数的一次和",
        "原创目标sum(w^2)，正负参数不能抵消正则惩罚；是否包含偏置另在任务规范声明。",
        "ml-linear",
        "weights=[1,-1] if n==1 else [1,0]\nprint(sum(weights))",
        "sum(weights)",
        "sum(w*w for w in weights)",
        "0\n",
        "2\n",
        "1\n",
        "1\n",
        "非负单位参数",
    ),
    (
        4,
        1,
        "过大学习率在二次目标上会发散",
        "实际标量梯度下降L=w^2/2，起点1，学习率3/0.5，20轮比较损失；该凸例不证明一般网络收敛。",
        "ml-linear",
        "w=1.;lr=3. if n==1 else .5;initial=w*w\nfor _ in range(20):w-=lr*w\nprint(w*w<initial)",
        "lr=3. if n==1 else .5",
        "lr=.5",
        "False\n",
        "True\n",
        "True\n",
        "True\n",
        "原学习率已稳定",
    ),
    (
        4,
        2,
        "低训练误差不能证明泛化",
        "原创给定训练0/验证9或0，须单列验证误差；记录不是实际拟合整个模型。",
        "ml-validation",
        "train_error=0;validation_error=9 if n==1 else 0\nprint(train_error)",
        "print(train_error)",
        "print(train_error,validation_error)",
        "0\n",
        "0 9\n",
        "0\n",
        "0 0\n",
        "两侧误差都低",
    ),
    (
        4,
        3,
        "超参数只能按验证集选择",
        "原创固定记录模型A验证1测试8/B验证2测试0，选型不能偷看测试；最终测试只报告一次。",
        "ml-validation",
        "validation={'A':1,'B':2};test={'A':8,'B':0} if n==1 else {'A':0,'B':8}\nprint(min(test,key=test.get))",
        "min(test,key=test.get)",
        "min(validation,key=validation.get)",
        "B\n",
        "A\n",
        "A\n",
        "A\n",
        "测试排序偶然一致",
    ),
    (
        5,
        1,
        "分裂不纯度按子节点样本数加权",
        "原创子节点2样本Gini0、8样本Gini1/2，平均值不应等权；只核对给定分裂。",
        "ml-tree",
        "from fractions import Fraction\nweights=[2,8] if n==1 else [5,5];gini=[Fraction(0),Fraction(1,2)]\nprint(sum(gini)/2)",
        "sum(gini)/2",
        "sum(w*g for w,g in zip(weights,gini))/sum(weights)",
        "1/4\n",
        "2/5\n",
        "1/4\n",
        "1/4\n",
        "等大子节点",
    ),
    (
        5,
        2,
        "bagging预测平均不可误用累加",
        "原创两个回归基学习器预测2/4，等权bagging取均值；本活动不实现完整boosting。",
        "ml-ensemble",
        "from fractions import Fraction\npredictions=[2,4] if n==1 else [3]\nprint(sum(predictions))",
        "sum(predictions)",
        "Fraction(sum(predictions),len(predictions))",
        "6\n",
        "3\n",
        "3\n",
        "3\n",
        "单基学习器",
    ),
    (
        5,
        3,
        "复杂度选型须观察验证风险",
        "原创给定两树训练误差深0/浅1，验证深8/浅2；选择验证低者，不以训练拟合替代泛化。",
        "ml-tree",
        "training={'deep':0,'shallow':1};validation={'deep':8 if n==1 else 0,'shallow':2}\nprint(min(training,key=training.get))",
        "min(training,key=training.get)",
        "min(validation,key=validation.get)",
        "deep\n",
        "shallow\n",
        "deep\n",
        "deep\n",
        "深树验证更好",
    ),
    (
        6,
        1,
        "最近邻应选择最小距离",
        "真实一维1NN，训练坐标0标A和10标B，查询1/5，平局按输入次序稳定。",
        "ml-neighbor",
        "points=[(0,'A'),(10,'B')];query=1 if n==1 else 5\nprint(max(points,key=lambda p:abs(p[0]-query))[1])",
        "max(points,key=",
        "min(points,key=",
        "B\n",
        "A\n",
        "A\n",
        "A\n",
        "等距查询",
    ),
    (
        6,
        2,
        "特征尺度改变距离排序",
        "原创二维查询原点，A=(1,100),B=(5,0)，第二维给定尺度100；缩放必须预先在训练过程冻结。",
        "ml-neighbor",
        "points=[(1,100,'A'),(5,0,'B')] if n==1 else [(1,0,'A'),(5,0,'B')]\nprint(min(points,key=lambda p:p[0]**2+p[1]**2)[2])",
        "p[0]**2+p[1]**2",
        "p[0]**2+(p[1]/100)**2",
        "B\n",
        "A\n",
        "A\n",
        "A\n",
        "第二维无贡献",
    ),
    (
        6,
        3,
        "线性特征无法表示对称两端类别",
        "原创标签规则abs(x)>1，特征x的阈值不能表示两端，特征x平方阈值可；这是显式非线性映射，非完整核SVM。",
        "ml-linear",
        "xs=[-2,0,2] if n==1 else [0,2]\ntruth=[abs(x)>1 for x in xs];pred=[x>1 for x in xs]\nprint(sum(a!=b for a,b in zip(truth,pred)))",
        "pred=[x>1 for x in xs]",
        "pred=[x*x>1 for x in xs]",
        "1\n",
        "0\n",
        "0\n",
        "0\n",
        "只有非负输入",
    ),
    (
        7,
        1,
        "k均值中心应为簇内算术均值",
        "原创单簇样本0/2/10，中心不能取第一个点；多簇分配及初始化需另外验证。",
        "ml-cluster",
        "from fractions import Fraction\ncluster=[0,2,10] if n==1 else [4,4]\nprint(cluster[0])",
        "cluster[0]",
        "Fraction(sum(cluster),len(cluster))",
        "0\n",
        "4\n",
        "4\n",
        "4\n",
        "完全重合簇",
    ),
    (
        7,
        2,
        "PCA投影必须沿用训练中心",
        "原创预先冻结单位主轴(1,0)与训练均值(3,3)，投影(5,3)应2；不宣称从这例计算协方差特征分解。",
        "ml-pca",
        "point=(5,3) if n==1 else (0,3);mean=(3,3);axis=(1,0)\nprint(sum(x*v for x,v in zip(point,axis)))",
        "sum(x*v for x,v in zip(point,axis))",
        "sum((x-m)*v for x,m,v in zip(point,mean,axis))",
        "5\n",
        "2\n",
        "0\n",
        "-3\n",
        "改变投影点",
    ),
    (
        7,
        3,
        "聚类编号置换不代表分组变化",
        "原创两分区[0,0,1,1]与[1,1,0,0]等价，比较同簇对关系不按数字标签匹配。",
        "ml-cluster",
        "a=[0,0,1,1];b=[1,1,0,0] if n==1 else a\nprint(a==b)",
        "a==b",
        "all((a[i]==a[j])==(b[i]==b[j]) for i in range(len(a)) for j in range(len(a)))",
        "False\n",
        "True\n",
        "True\n",
        "True\n",
        "编号未置换",
    ),
    (
        8,
        1,
        "反向传播必须应用链式输入因子",
        "原创标量神经元z=w*x，L=z^2/2，无偏置或非线性；dL/dw=z*x，不把dL/dz当权重梯度。",
        "ml-backprop",
        "w=1;x=3 if n==1 else 1;z=w*x\nprint(z)",
        "print(z)",
        "print(z*x)",
        "3\n",
        "9\n",
        "1\n",
        "1\n",
        "单位输入",
    ),
    (
        8,
        2,
        "训练更新应沿负梯度",
        "实际一输入一输出线性神经元训练y=2x，样本1/2，20轮平均平方损失梯度，稳定学习率0.1；非完整非线性MLP。",
        "ml-backprop",
        "w=0.;data=[(1.,2.),(2.,4.)] if n==1 else [(1.,2.)]\ndef loss():return sum((w*x-y)**2 for x,y in data)/len(data)\ninitial=loss()\nfor _ in range(20):\n grad=sum((w*x-y)*x for x,y in data)/len(data);w+=.1*grad\nprint(loss()<initial)",
        "w+=.1*grad",
        "w-=.1*grad",
        "False\n",
        "True\n",
        "False\n",
        "True\n",
        "单样本训练",
    ),
    (
        8,
        3,
        "稳定softmax先减最大logit",
        "真实math.exp浮点：1000/1001直接指数溢出；减最大保持比值并归一化。只检验此输入数值稳定性。",
        "ml-math",
        "import math\nlogits=[1000.,1001.] if n==1 else [0.,1.]\ntry:\n weights=[math.exp(x) for x in logits];p=[w/sum(weights) for w in weights];print(abs(sum(p)-1)<1e-12)\nexcept OverflowError:print('overflow')",
        "math.exp(x)",
        "math.exp(x-max(logits))",
        "overflow\n",
        "True\n",
        "True\n",
        "True\n",
        "有限小logit",
    ),
    (
        9,
        1,
        "精确率分母包含假阳性",
        "原创计数TP1/FP3/FN1，precision=1/4而非recall=1/2；零分母策略需单列。",
        "ml-metric",
        "from fractions import Fraction\ntp=1;fp=3 if n==1 else 1;fn=1\nprint(Fraction(tp,tp+fn))",
        "Fraction(tp,tp+fn)",
        "Fraction(tp,tp+fp)",
        "1/2\n",
        "1/4\n",
        "1/2\n",
        "1/2\n",
        "假阳性与假阴性同数",
    ),
    (
        9,
        2,
        "不平衡数据需独立观察少数类",
        "原创混淆计数TN99/TP0/FN1，准确率99/100但召回0；不等于已解决不平衡训练。",
        "ml-metric",
        "from fractions import Fraction\ntn=99 if n==1 else 1;tp=0;fn=1\nprint(Fraction(tn+tp,tn+tp+fn))",
        "Fraction(tn+tp,tn+tp+fn)",
        "Fraction(tp,tp+fn)",
        "99/100\n",
        "0\n",
        "1/2\n",
        "0\n",
        "均衡正负样本",
    ),
    (
        9,
        3,
        "点估计相同不能忽略样本数",
        "原创准确率1/1和100/100，点估计均为1，保留分子分母支撑不确定性讨论；不生成未经验证置信区间。",
        "ml-metric",
        "correct=1 if n==1 else 100;total=correct\nprint(correct/total)",
        "print(correct/total)",
        "print(correct,total)",
        "1.0\n",
        "1 1\n",
        "1.0\n",
        "100 100\n",
        "更大样本记录",
    ),
    (
        10,
        1,
        "实验记录必须冻结种子和数据版本",
        "原创实验metadata检查，字段齐全只是可追溯入口，不能代替实际复现。",
        "ml-validation",
        "run={'seed':7,'data_version':'synthetic-v1'}\nif n==2:run['split_version']='split-v1'\nprint('seed' in run)",
        "'seed' in run",
        "all(k in run for k in ['seed','data_version','split_version'])",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "划分版本已保存",
    ),
    (
        10,
        2,
        "模型持久化应包含预处理参数",
        "实际JSON文件保存权重2及训练中心3，重新读入预测x=5应4；只用本例JSON schema，不加载用户pickle。",
        "ml-save",
        "import json\nfrom pathlib import Path\nmodel={'weight':2,'mean':3};x=5 if n==1 else 3\nPath('model.json').write_text(json.dumps(model));restored=json.loads(Path('model.json').read_text())\nprint(restored['weight']*x)",
        "restored['weight']*x",
        "restored['weight']*(x-restored['mean'])",
        "10\n",
        "4\n",
        "6\n",
        "0\n",
        "输入等于训练中心",
    ),
    (
        10,
        3,
        "分布外输入应保留用途限制",
        "原创模型训练支持0到10输入，20为范围外，须标记核验而非沿用训练成绩；范围检查不能检测所有分布漂移。",
        "ml-leak",
        "x=20 if n==1 else 5\nprint('validated')",
        "print('validated')",
        "print('needs_review' if x<0 or x>10 else 'in_scope')",
        "validated\n",
        "needs_review\n",
        "validated\n",
        "in_scope\n",
        "声明支持范围内",
    ),
]
for row in CASES:
    add(*row)
if __name__ == "__main__":
    book.package["relations"] = []
    for module in range(1, 11):
        for left, right in [(1, 2), (2, 3)]:
            book.package["relations"].append(
                {
                    "from": f"CS13-M{module:02d}-O{left:02d}",
                    "to": f"CS13-M{module:02d}-O{right:02d}",
                    "kind": "conceptual_association",
                    "reason": "实验条件对照："
                    + CASES[(module - 1) * 3 + left - 1][2]
                    + "与"
                    + CASES[(module - 1) * 3 + right - 1][2],
                    "source_locator": CASES[(module - 1) * 3 + right - 1][4],
                    "course_version_id": book.version,
                    "review_state": "authority_checked",
                    "source": "原创实验工件关联，非课程次序生成严格先修；专业审校不可用。",
                }
            )
    book.save("CS13-core")
