"""Original networking exercises: local protocol APIs and explicit finite models."""

from pathlib import Path

from code_authoring import CodeBook

ROOT = Path(__file__).resolve().parents[2]
book = CodeBook(
    ROOT,
    "CS08-core-scope-0.1.0",
    "CS08-core-practice-0.1.0",
    "局部真实 TCP/UDP/HTTP 与明示协议模型；完整网桥、VLAN、FRR、抓包及重建实验待建设。",
    course="CS08",
    standard="code-fixed-condition-v1",
)
SOURCES = [
    (
        "net-socket",
        "Python3.13 socket",
        "https://docs.python.org/3.13/library/socket.html",
        "recv, shutdown, recvfrom, bind and timeout",
    ),
    (
        "net-ip",
        "Python3.13 ipaddress",
        "https://docs.python.org/3.13/library/ipaddress.html",
        "network membership, usable hosts including /31 and /32",
    ),
    (
        "net-tcp",
        "RFC9293 TCP",
        "https://www.rfc-editor.org/rfc/rfc9293.html",
        "2.2 byte stream; 3.8 flow control; original finite examples",
    ),
    (
        "net-ipv6",
        "RFC8200 IPv6",
        "https://www.rfc-editor.org/rfc/rfc8200.html",
        "4.5 and 5 source fragmentation, router restriction",
    ),
    (
        "net-http",
        "RFC9110 HTTP Semantics",
        "https://www.rfc-editor.org/rfc/rfc9110.html",
        "15.5.4 403; requests and responses",
    ),
    (
        "net-frame",
        "Systems Approach Framing",
        "https://github.com/SystemsApproach/book/blob/master/direct/framing.rst",
        "2.3.2 sentinel and stuffing",
    ),
    (
        "net-crc",
        "Systems Approach Error Detection",
        "https://github.com/SystemsApproach/book/blob/master/direct/error.rst",
        "2.4 modulo two polynomial remainder",
    ),
    (
        "net-mac",
        "Systems Approach Ethernet",
        "https://github.com/SystemsApproach/book/blob/master/direct/ethernet.rst",
        "2.6 shared medium vs modern point-to-point",
    ),
    (
        "net-switch",
        "Systems Approach Ethernet Switching",
        "https://github.com/SystemsApproach/book/blob/master/internetworking/ethernet.rst",
        "learning bridges and spanning tree; finite VLAN example is original",
    ),
    (
        "net-prefix",
        "RFC4632 CIDR",
        "https://www.rfc-editor.org/rfc/rfc4632.html",
        "5.1 longest-match forwarding",
    ),
    (
        "net-arp",
        "RFC826 ARP",
        "https://www.rfc-editor.org/rfc/rfc826.html",
        "protocol address to local hardware address mapping",
    ),
    (
        "net-nd",
        "RFC4861 Neighbor Discovery",
        "https://www.rfc-editor.org/rfc/rfc4861.html",
        "3.1, 7.1 solicitation hop limit validation",
    ),
    (
        "net-udp",
        "RFC768 UDP",
        "https://www.rfc-editor.org/rfc/rfc768.html",
        "datagram service; no guaranteed delivery or duplicate protection",
    ),
    (
        "net-dns",
        "RFC1035 DNS",
        "https://www.rfc-editor.org/rfc/rfc1035.html",
        "4.1.1 transaction ID and QR; TTL; original limited responder",
    ),
    (
        "net-wireless",
        "Systems Approach Wireless",
        "https://github.com/SystemsApproach/book/blob/master/direct/wireless.rst",
        "2.7 hidden terminals at receiver",
    ),
    (
        "net-tls",
        "RFC8446 TLS1.3",
        "https://www.rfc-editor.org/rfc/rfc8446.html",
        "1 channel authentication confidentiality integrity; application authorization separate",
    ),
    (
        "net-hmac",
        "Python3.13 hmac",
        "https://docs.python.org/3.13/library/hmac.html",
        "keyed integrity and compare_digest; no encryption",
    ),
]
book.package["sources"] = [
    {
        "id": key,
        "title": title,
        "url": url,
        "locator": locator,
        "status": "authority_checked",
        "checked_at": "2026-10-10",
    }
    for key, title, url, locator in SOURCES
]
book.package["activities"] = []


def add(
    module,
    objective,
    title,
    theory,
    source,
    code,
    wrong,
    right,
    before,
    after,
    changed_before,
    changed_after,
    variant,
):
    goal = f"CS08-M{module:02d}-O{objective:02d}"
    initial = "n = int(input())\n" + code.strip() + "\n"
    assert wrong in initial, goal
    repaired = initial.replace(wrong, right)
    cases = []
    for task, label, stdin, first, second in [
        ("base", title, "1\n", before, after),
        ("changed-condition", variant, "2\n", changed_before, changed_after),
    ]:
        request = {
            "language": "python313",
            "entry": "main.py",
            "files": {"main.py": initial},
            "stdin": stdin,
        }
        answer = {**request, "files": {"main.py": repaired}}
        cases.append(
            (
                task,
                label,
                "先写输入约束及预测，运行并保存反例，修改后解释哪些结论尚未证明。",
                request,
                answer,
                first,
                second,
            )
        )
    book.add(
        goal,
        title,
        "标注契约与证据，再用实际运行定位违反条件的步骤。",
        [
            theory,
            "本例的固定运行只支持列出的观察；证明、一般界和独立迁移不由输出代替。",
        ],
        [
            "先区分输出错误、输入前提变化和论证缺口。",
            "检查最小反例与边界，并解释修改依据。",
        ],
        [source],
        cases,
    )


add(
    1,
    1,
    "教学封装顺序保留层次",
    "本例规定从外到内为 Ethernet/IP/TCP/application，不是完整报文字节解析；解封装应先移除外层。",
    "net-tcp",
    "layers=['Ethernet','IP','TCP','application'] if n==1 else ['IP','UDP','application']\nprint(layers[-1])",
    "layers[-1]",
    "layers[0]",
    "application\n",
    "Ethernet\n",
    "application\n",
    "IP\n",
    "换用 UDP 承载",
)
add(
    1,
    2,
    "串行化和传播时延分别计单位",
    "原创无排队单链路：8000 bit、速率 2000 bit/s、传播 1s；长度除速率，再加传播。不得把往返和单程混用。",
    "net-mac",
    "bits=8000 if n==1 else 0\nrate=2000\npropagation=1\nprint(bits//rate)",
    "print(bits//rate)",
    "print(bits//rate+propagation)",
    "4\n",
    "5\n",
    "0\n",
    "1\n",
    "零长度仍有传播模型项",
)
add(
    1,
    3,
    "串联路径的理想瓶颈上界",
    "原创持续流、忽略开销与竞争的两段串联链路上界为较小容量，实际吞吐仍须测量。",
    "net-mac",
    "rates=[10,2] if n==1 else [4,4]\nprint(max(rates))",
    "max(rates)",
    "min(rates)",
    "10\n",
    "2\n",
    "4\n",
    "4\n",
    "等容量链路",
)
add(
    2,
    1,
    "教学字节定界必须转义载荷",
    "原创帧使用 ~ 为边界、} 为转义，载荷内两者都前置 }；这是自定义教学编码，不是直接实现 PPP。",
    "net-frame",
    "payload='a~b' if n==1 else 'ab'\nencoded=payload\nprint('~'+encoded+'~')",
    "encoded=payload",
    "encoded=''.join(('}'+c) if c in '~}' else c for c in payload)",
    "~a~b~\n",
    "~a}~b~\n",
    "~ab~\n",
    "~ab~\n",
    "不含保留字符",
)
add(
    2,
    2,
    "CRC 使用模二除法而非整数余数",
    "原创生成多项式 1011，收到的位串直接作 GF(2) 除法；余数非零说明检出错误，零不能证明绝无错误。尚未承载停止等待重传目标全部条件。",
    "net-crc",
    "word=0b1101 if n==1 else 0\ngenerator=0b1011\nx=word\nwhile x.bit_length()>=generator.bit_length():\n x^=generator<<(x.bit_length()-generator.bit_length())\nprint(word%generator)",
    "word%generator",
    "x",
    "2\n",
    "6\n",
    "0\n",
    "0\n",
    "全零位串",
)
add(
    2,
    3,
    "现代全双工链路不运行共享碰撞规则",
    "对明示 full_duplex/shared 模式选择是否适用经典 CSMA/CD；并非交换式以太网全部共享碰撞域，也不模拟真实退避。",
    "net-mac",
    "mode='full_duplex' if n==1 else 'shared'\nprint(True)",
    "print(True)",
    "print(mode=='shared')",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "共享半双工教学介质",
)
add(
    3,
    1,
    "MAC 学习绑定收到帧的源地址",
    "原创学习表：收到帧的源 MAC 与入口绑定，目的 MAC 用于查询。只核验表更新，非真实网桥。",
    "net-switch",
    "source='A';destination='B' if n==1 else 'A'\nport=1;table={}\ntable[destination]=port\nprint(table.get(source,'unknown'))",
    "table[destination]=port",
    "table[source]=port",
    "unknown\n",
    "1\n",
    "1\n",
    "1\n",
    "源目的相同的观察条件",
)
add(
    3,
    2,
    "VLAN 教学分区须检查禁止通信",
    "原创二层无路由模型：VLAN 不同不可直接转发；此布尔模型不是实际 VLAN 配置或连通证据。",
    "net-switch",
    "left=10;right=20 if n==1 else 10\nprint(True)",
    "print(True)",
    "print(left==right)",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "同 VLAN 条件",
)
add(
    3,
    3,
    "广播环路需切断转发环",
    "原创三网桥图使用无向连通 DFS 检测环，不实现 STP 选举／BPDU，输出不能当真实交换设备状态。",
    "net-switch",
    "edges=[('A','B'),('B','C'),('C','A')] if n==1 else [('A','B'),('B','C')]\nparent={}\ndef root(x):\n parent.setdefault(x,x)\n while parent[x]!=x:x=parent[x]\n return x\ncycle=False\nfor a,b in edges:\n ra,rb=root(a),root(b)\n if ra==rb:cycle=True\n else:parent[ra]=rb\nprint(False)",
    "print(False)",
    "print(cycle)",
    "False\n",
    "True\n",
    "False\n",
    "False\n",
    "移除一条边",
)
add(
    4,
    1,
    "IPv4 可用地址不能一律减二",
    "使用真实 ipaddress API：普通 /30 有两个可用主机，/31 点到点语义含两个端点。此任务只做地址规划，不配置接口。",
    "net-ip",
    "import ipaddress\nprefix=30 if n==1 else 31\nnet=ipaddress.ip_network('192.0.2.0/'+str(prefix))\nprint(net.num_addresses-2)",
    "net.num_addresses-2",
    "len(list(net.hosts()))",
    "2\n",
    "2\n",
    "0\n",
    "2\n",
    "点到点 /31",
)
add(
    4,
    2,
    "IPv6 邻居请求必须验证 Hop Limit",
    "对原创报文字段记录检查 ND 的 Hop Limit=255 条件，避免接受经路由转发的请求；只是一项必要条件，尚须 ICMPv6 校验和及地址规则。",
    "net-nd",
    "hop=64 if n==1 else 255\nprint(True)",
    "print(True)",
    "print(hop==255)",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "合法 Hop Limit",
)
add(
    4,
    3,
    "下一跳网关须按接口前缀核对",
    "原创明确在链路网关场景：192.0.2.2/24 的下一跳必须在本地前缀内；特殊 onlink 与隧道例外不在题面。不构成真实接口配置。",
    "net-ip",
    "import ipaddress\nlocal=ipaddress.ip_interface('192.0.2.2/24')\ngateway=ipaddress.ip_address('198.51.100.1' if n==1 else '192.0.2.1')\nprint(True)",
    "print(True)",
    "print(gateway in local.network)",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "换成本地下一跳",
)
add(
    5,
    1,
    "最长前缀须在所有匹配项中选择",
    "原创路由表先列默认，再列 /24；顺序不是前缀优先级。相同前缀的管理距离或多路径不在本例。",
    "net-prefix",
    "import ipaddress\naddress=ipaddress.ip_address('192.0.2.9' if n==1 else '198.51.100.9')\nroutes=[(ipaddress.ip_network('0.0.0.0/0'),'default'),(ipaddress.ip_network('192.0.2.0/24'),'local')]\nmatches=[r for r in routes if address in r[0]]\nprint(matches[0][1])",
    "matches[0][1]",
    "max(matches,key=lambda r:r[0].prefixlen)[1]",
    "default\n",
    "local\n",
    "default\n",
    "default\n",
    "仅匹配默认路由",
)
add(
    5,
    2,
    "静态路径需同时考虑回程",
    "原创方向图分别核对请求路径和返回路径，正向可达不保证往返。不是 FRR 路由生效证据。",
    "net-prefix",
    "forward=True;reverse=False if n==1 else True\nprint(forward)",
    "print(forward)",
    "print(forward and reverse)",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "补上返回方向",
)
add(
    5,
    3,
    "断链后只在现存路径中重算",
    "原创小图最短路径重算，断开 A-B 后应经 C 到 B；这是图模型而非 OSPF 收敛时序或真实 FRR。",
    "net-prefix",
    "edges={'A':[('C',2)],'C':[('B',2)],'B':[]} if n==1 else {'A':[('B',1)],'B':[]}\ndist={'A':0};todo=[(0,'A')]\nimport heapq\nwhile todo:\n cost,node=heapq.heappop(todo)\n if cost!=dist[node]:continue\n for target,weight in edges[node]:\n  value=cost+weight\n  if value<dist.get(target,999):dist[target]=value;heapq.heappush(todo,(value,target))\nprint(1)",
    "print(1)",
    "print(dist['B'])",
    "1\n",
    "4\n",
    "1\n",
    "1\n",
    "恢复直接链路",
)
add(
    6,
    1,
    "ARP 查询本链路下一跳而非远端主机",
    "原创有网关的 IPv4 路径：远端服务的目的 IP 保持不变，本链路 ARP 查询下一跳网关；本例未发送真实 ARP/ICMP。",
    "net-arp",
    "destination='198.51.100.8' if n==1 else '192.0.2.8'\ngateway='192.0.2.1'\nimport ipaddress\nonlink=ipaddress.ip_address(destination) in ipaddress.ip_network('192.0.2.0/24')\nprint(destination)",
    "print(destination)",
    "print(destination if onlink else gateway)",
    "198.51.100.8\n",
    "192.0.2.1\n",
    "192.0.2.8\n",
    "192.0.2.8\n",
    "目的就在本链路",
)
add(
    6,
    2,
    "IPv6 路由器不能分片超 MTU 报文",
    "原创记录仅判断路由器遇到超 MTU 时选择 Packet Too Big；IPv6 分片仅源端可做，此处不发送真实 ICMPv6。",
    "net-ipv6",
    "size=1500 if n==1 else 1280\nmtu=1280\nprint('forward')",
    "print('forward')",
    "print('packet_too_big' if size>mtu else 'forward')",
    "forward\n",
    "packet_too_big\n",
    "forward\n",
    "forward\n",
    "恰好 MTU",
)
add(
    6,
    3,
    "教学 NAT 映射不能替代过滤授权",
    "原创两项独立条件：存在地址转换映射且过滤允许才能通过；不是实际 NAT conntrack 或防火墙配置。",
    "net-http",
    "mapped=True;allowed=False if n==1 else True\nprint(mapped)",
    "print(mapped)",
    "print(mapped and allowed)",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "允许的映射流",
)
add(
    7,
    1,
    "真实 TCP 半关闭后仍可读取响应",
    "仅本沙箱 IPv4 回环：客户端 shutdown(SHUT_WR) 后服务端读 EOF，再回送长度；接收方向仍开放。没有抓包，不能声称观察三次握手细节。",
    "net-socket",
    "import socket,threading\npayload=b'alpha' if n==1 else b'xy'\nserver=socket.socket();server.settimeout(2);server.bind(('127.0.0.1',0));server.listen()\ndef serve():\n with server.accept()[0] as conn:\n  conn.settimeout(2);data=b''\n  while True:\n   chunk=conn.recv(2)\n   if not chunk:break\n   data+=chunk\n  conn.sendall(str(len(data)).encode())\nthread=threading.Thread(target=serve);thread.start()\nwith socket.socket() as client:\n client.settimeout(2);client.connect(server.getsockname());client.sendall(payload);client.shutdown(socket.SHUT_WR)\n reply=client.recv(8)\n print('closed')\nthread.join();server.close()",
    "print('closed')",
    "print(reply.decode())",
    "closed\n",
    "5\n",
    "closed\n",
    "2\n",
    "改变请求载荷长度",
)
add(
    7,
    2,
    "发送额度受接收及拥塞窗口共同限制",
    "原创静态字节窗口模型：可发新数据=min(rwnd,cwnd)-flight，不低于零。没有实现重传、拥塞算法或真实时延丢包测量。",
    "net-tcp",
    "rwnd=3;cwnd=10;flight=2 if n==1 else 3\nprint(max(0,cwnd-flight))",
    "cwnd-flight",
    "min(rwnd,cwnd)-flight",
    "8\n",
    "1\n",
    "7\n",
    "0\n",
    "接收窗口已满",
)
add(
    7,
    3,
    "真实 UDP 截断不保留数据报尾部",
    "仅本沙箱 UDP 回环：首次 recvfrom(2) 截断较长数据报，下一次读到下一报，不会接续上一报的尾部；不证明可靠性。",
    "net-udp",
    "import socket\nwith socket.socket(socket.AF_INET,socket.SOCK_DGRAM) as receiver, socket.socket(socket.AF_INET,socket.SOCK_DGRAM) as sender:\n receiver.bind(('127.0.0.1',0));receiver.settimeout(2)\n sender.sendto(b'alpha' if n==1 else b'xy',receiver.getsockname());sender.sendto(b'Z',receiver.getsockname())\n first=receiver.recvfrom(2)[0];second=receiver.recvfrom(8)[0]\n print((first+second).decode())",
    "print((first+second).decode())",
    "print(second.decode())",
    "alZ\n",
    "Z\n",
    "xyZ\n",
    "Z\n",
    "第一报恰好两字节",
)
add(
    8,
    1,
    "真实 UDP DNS 应答需对应事务编号",
    "原创仅含 12 字节头的本地 DNS 格式应答器：检查 ID 及 QR，不支持完整递归、压缩名或记录；不能据此认定 DNS 解析功能完成。",
    "net-dns",
    "import socket,struct,threading\nidentifier=7\nwith socket.socket(socket.AF_INET,socket.SOCK_DGRAM) as server,socket.socket(socket.AF_INET,socket.SOCK_DGRAM) as client:\n server.bind(('127.0.0.1',0));server.settimeout(2);client.settimeout(2)\n def respond():\n  query,address=server.recvfrom(512)\n  server.sendto(struct.pack('!HHHHHH',8 if n==1 else 7,0x8000,0,0,0,0),address)\n thread=threading.Thread(target=respond);thread.start()\n client.sendto(struct.pack('!HHHHHH',identifier,0,0,0,0,0),server.getsockname())\n response=client.recvfrom(512)[0];thread.join()\n response_id,flags=struct.unpack('!HH',response[:4])\n print(bool(flags&0x8000))",
    "print(bool(flags&0x8000))",
    "print(response_id==identifier and bool(flags&0x8000))",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "对应的事务编号",
)
add(
    8,
    2,
    "真实 HTTP 字节响应先分头再读正文",
    "仅回环 TCP 实际交换 HTTP/1.1，Connection: close 和 Content-Length 明确，读取到 EOF 再解析；本任务不是通用 HTTP 解析器，不支持分块、压缩或 HTTP2。",
    "net-http",
    "import socket,threading\nbody=b'ok' if n==1 else b'hello'\nserver=socket.socket();server.settimeout(2);server.bind(('127.0.0.1',0));server.listen()\ndef serve():\n with server.accept()[0] as conn:\n  conn.settimeout(2);request=b''\n  while b'\\r\\n\\r\\n' not in request:request+=conn.recv(4096)\n  conn.sendall(b'HTTP/1.1 200 OK\\r\\nConnection: close\\r\\nContent-Length: '+str(len(body)).encode()+b'\\r\\n\\r\\n'+body)\nthread=threading.Thread(target=serve);thread.start()\nwith socket.socket() as client:\n client.settimeout(2);client.connect(server.getsockname());client.sendall(b'GET / HTTP/1.1\\r\\nHost: lab.test\\r\\nConnection: close\\r\\n\\r\\n');raw=b''\n while True:\n  chunk=client.recv(2)\n  if not chunk:break\n  raw+=chunk\n print(raw.split(b'\\r\\n')[0].decode())\nthread.join();server.close()",
    "print(raw.split(b'\\r\\n')[0].decode())",
    "print(raw.split(b'\\r\\n\\r\\n',1)[1].decode())",
    "HTTP/1.1 200 OK\n",
    "ok\n",
    "HTTP/1.1 200 OK\n",
    "hello\n",
    "更长的 HTTP 正文",
)
add(
    8,
    3,
    "TLS 通过不等于应用授权通过",
    "原创分层判断：证书校验通过但 HTTP403 仍拒绝业务请求；布尔输入是给定证据，不是本实验 TLS 握手结果。",
    "net-tls",
    "tls_ok=True;http_status=403 if n==1 else 200\nprint(tls_ok)",
    "print(tls_ok)",
    "print(tls_ok and http_status==200)",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "应用允许访问",
)
add(
    9,
    1,
    "隐藏终端在接收端仍可能冲突",
    "原创无线可达关系：A 和 C 互相听不到但都能到 B，同时发送可在 B 冲突；未模拟功率、退避或真实无线设备。",
    "net-wireless",
    "hear_each_other=False;at_receiver=2 if n==1 else 1\nprint(hear_each_other)",
    "print(hear_each_other)",
    "print(at_receiver>1)",
    "False\n",
    "True\n",
    "False\n",
    "False\n",
    "只有一个发送者",
)
add(
    9,
    2,
    "真实 HMAC 检验篡改不提供加密",
    "用公开教学密钥 hmac SHA256 对比原消息与改动消息，compare_digest 返回完整性验证结果；密钥公开不能保护真实通信，HMAC 不隐藏明文。",
    "net-hmac",
    "import hmac\nkey=b'public-teaching-key';message=b'pay=1'\ntag=hmac.digest(key,message,'sha256')\nreceived=b'pay=9' if n==1 else message\nexpected=hmac.digest(key,received,'sha256')\nprint(True)",
    "print(True)",
    "print(hmac.compare_digest(tag,expected))",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "未改动的明文",
)
add(
    9,
    3,
    "有效认证标签也需要防重放状态",
    "原创请求序号集合：同一有效序号第二次拒绝；本例给定 tag_valid，不构成 TLS replay 检查器或网络攻击实验。",
    "net-tls",
    "seen={1};sequence=1 if n==1 else 2;tag_valid=True\nprint(tag_valid)",
    "print(tag_valid)",
    "print(tag_valid and sequence not in seen)",
    "True\n",
    "False\n",
    "True\n",
    "True\n",
    "新序号请求",
)
add(
    10,
    1,
    "服务排障需提出可检验的分层假设",
    "原创提供 DNS 成功、TCP 拒绝、HTTP 未执行的证据；应优先检查端口监听／连接，不从 DNS 成功推定应用成功。实际故障原因仍需新证据。",
    "net-http",
    "dns_ok=True;tcp_ok=False if n==1 else True\nprint('application')",
    "print('application')",
    "print('application' if tcp_ok else 'tcp_listener')",
    "application\n",
    "tcp_listener\n",
    "application\n",
    "application\n",
    "TCP 成功后再查应用",
)
add(
    10,
    2,
    "真实回环拒绝与监听成功分别取证",
    "在本沙箱建立监听 socket，另占用但不 listen 的端口，分别 connect_ex；拒绝说明该时刻连接未建立，不能由此推定所有故障原因。",
    "net-socket",
    "import socket\nwith socket.socket() as service,socket.socket() as unused,socket.socket() as client:\n service.bind(('127.0.0.1',0));service.listen();unused.bind(('127.0.0.1',0));client.settimeout(2)\n address=unused.getsockname() if n==1 else service.getsockname()\n error=client.connect_ex(address)\n print('connected')",
    "print('connected')",
    "print('connected' if error==0 else 'refused')",
    "connected\n",
    "refused\n",
    "connected\n",
    "connected\n",
    "目标端口处于监听状态",
)
add(
    10,
    3,
    "真实服务重建后重新核对通信",
    "本沙箱顺序创建两个独立 UDP 服务实例，端口由内核分配。第二次需实际通信验证，不把第一次输出当新环境证据；不构成双网段拓扑完整恢复项目。",
    "net-socket",
    "import socket\nresults=[]\nfor payload in [b'first',b'second' if n==1 else b'first']:\n with socket.socket(socket.AF_INET,socket.SOCK_DGRAM) as server,socket.socket(socket.AF_INET,socket.SOCK_DGRAM) as client:\n  server.bind(('127.0.0.1',0));server.settimeout(2);client.sendto(payload,server.getsockname());results.append(server.recvfrom(64)[0].decode())\nprint(results[0])",
    "print(results[0])",
    "print(results[-1])",
    "first\n",
    "second\n",
    "first\n",
    "first\n",
    "相同载荷仍须实际重跑",
)

if __name__ == "__main__":
    book.package["relations"] = []
    # Local relations are specific claims, not inferred prerequisites from numbering.
    links = [
        (1, 1, 2, "net-tcp", "分层封装增加实际传输字节，时延计算须标注层次"),
        (1, 2, 3, "net-mac", "单链路串行化时间与串联瓶颈分别约束性能"),
        (2, 1, 2, "net-frame", "定界与校验分别处理边界和内容错误"),
        (2, 2, 3, "net-mac", "差错检出不能取代介质访问规则"),
        (3, 1, 2, "net-switch", "转发表学习需要保留广播域范围"),
        (3, 2, 3, "net-switch", "VLAN 分区与广播环路是不同条件"),
        (4, 1, 3, "net-ip", "本地前缀决定普通 onlink 下一跳约束"),
        (4, 2, 3, "net-nd", "接口下一跳解析在 IPv6 使用邻居发现"),
        (5, 1, 2, "net-prefix", "双向路径分别选择相应目的最长前缀"),
        (5, 2, 3, "net-prefix", "断链后需重新检查可用返回路径"),
        (6, 1, 2, "net-ipv6", "本地下一跳解析与路径 MTU 是不同层的检查"),
        (6, 2, 3, "net-http", "服务不可达还需区分超 MTU 与过滤条件"),
        (7, 1, 2, "net-tcp", "TCP 生命周期与字节窗口是不同运行约束"),
        (7, 1, 3, "net-udp", "字节流与数据报的边界及关闭语义不同"),
        (8, 1, 2, "net-http", "名称解析输出只提供地址，不保证 HTTP 响应"),
        (8, 2, 3, "net-http", "HTTP 业务拒绝与安全传输通道必须分开定位"),
        (9, 1, 2, "net-wireless", "物理碰撞和消息完整性是不同失败来源"),
        (9, 2, 3, "net-hmac", "标签验证与序号防重放需不同证据"),
        (10, 1, 2, "net-socket", "连接假设必须通过新的实际端口观察取证"),
        (10, 2, 3, "net-socket", "重建后不能沿用旧端口与历史连接结果"),
    ]
    for module, left, right, source, reason in links:
        book.package["relations"].append(
            {
                "from": f"CS08-M{module:02d}-O{left:02d}",
                "to": f"CS08-M{module:02d}-O{right:02d}",
                "kind": "conceptual_association",
                "reason": reason,
                "source_locator": source,
                "course_version_id": book.version,
                "review_state": "authority_checked",
                "source": "原创工件关系："
                + reason
                + "；机制参见 "
                + source
                + "；专业审校不可用。",
            }
        )
    book.save("CS08-core")
