"""Second immutable CS03 package: bounded practice for each of thirty goals."""

from uuid import NAMESPACE_URL, uuid5

import build_cs03_linear as linear

book = linear.book
book.name = "CS03-core-practice-0.2.0"
book.version = str(uuid5(NAMESPACE_URL, "vault:" + book.name))
book.package.update(
    course_version_id=book.version,
    version=book.name,
    scope_note="30 目标各有受限 C++17 实践；完整目标深度、结构轨迹、独立迁移、综合项目与专业审校未完成。",
)
for row in book.rows:
    row["version"] = book.version

SOURCES = [
    (
        "odsa-hash-delete",
        "OpenDSA Deletion in Open Addressing",
        "https://opendsax.cs.vt.edu/ODSA/StandaloneModules/20250507145027/html/HashDel.html",
        "Deletion: tombstones and continued search",
    ),
    (
        "cpp17-draft",
        "WG21 N4659 C++17 working draft",
        "https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/n4659.pdf",
        "8.6 [expr.mul] p.131: integral quotient and remainder",
    ),
    (
        "cornell-kmp",
        "Cornell CS312 String Search",
        "https://www.cs.cornell.edu/courses/cs312/2002fa/lectures/lec26.htm",
        "Knuth-Morris-Pratt Algorithm; prefix convention",
    ),
    (
        "scipy-coo",
        "SciPy COO sparse representation",
        "https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.html",
        "Notes: duplicate coordinates; construction",
    ),
    (
        "mit-trees",
        "MIT 6.006 Binary Trees",
        "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/376714cc85c6c784d90eec9c575ec027_MIT6_006S20_lec6.pdf",
        "pp.1–6: traversal, subtree operations, search trees",
    ),
    (
        "mit-avl",
        "MIT 6.006 AVL Trees",
        "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/a2c80596cf4a2b5fbc854afdd2f23dcb_MIT6_006S20_lec7.pdf",
        "rotation and balancing",
    ),
    (
        "odsa-huffman",
        "OpenDSA Huffman Coding Trees",
        "https://opendsax.cs.vt.edu/ODSA/Books/CS3/html/Huffman.html",
        "7.18.1.1 building and assigning codes",
    ),
    (
        "cmu-bplus",
        "CMU 15-445 Tree Indexes",
        "https://15445.courses.cs.cmu.edu/fall2022/notes/08-trees.pdf",
        "pp.1–2: leaf and internal node split differ",
    ),
    (
        "mit-bfs",
        "MIT 6.006 Breadth-First Search",
        "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/196a95604877d326c6586e60477b59d4_MIT6_006S20_lec9.pdf",
        "representations and BFS",
    ),
    (
        "mit-dfs",
        "MIT 6.006 Depth-First Search",
        "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/f3e349e0eb3288592289d2c81e0c4f4d_MIT6_006S20_lec10.pdf",
        "full graph search and topological order",
    ),
    (
        "mit-dijkstra",
        "MIT 6.006 Dijkstra",
        "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/d819e7f4568aced8d5b59e03db6c7b67_MIT6_006S20_lec13.pdf",
        "pp.1–2: nonnegative weights and relaxation",
    ),
    (
        "gordon-cpm",
        "Gordon College Graphs and Networks",
        "https://www.math-cs.gordon.edu/courses/cs321/lectures/graphs.html",
        "AOE critical path analysis; earliest/latest event times",
    ),
    (
        "mit-hash",
        "MIT 6.006 Hashing",
        "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/ce9e94705b914598ce78a00a70a1f734_MIT6_006S20_lec4.pdf",
        "hash functions, collisions and load",
    ),
    (
        "mit-sort",
        "MIT 6.006 Sorting",
        "https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-spring-2020/6d1ae5278d02bbecb5c4428928b24194_MIT6_006S20_lec3.pdf",
        "sorting permutation, insertion and merge",
    ),
    (
        "odsa-external",
        "OpenDSA External Sorting",
        "https://opendsax.cs.vt.edu/ODSA/Books/CS3/html/ExternalSort.html",
        "9.6 sorted runs and merging",
    ),
]
book.package["sources"].extend(
    {
        "id": key,
        "title": title,
        "url": url,
        "locator": locator,
        "checked_at": "2026-10-10",
        "status": "authority_checked",
    }
    for key, title, url, locator in SOURCES
)


def add(
    module,
    objective,
    title,
    theory,
    declarations,
    body,
    wrong,
    right,
    before,
    after,
    changed_before,
    changed_after,
    variant,
    source,
):
    extra = "#include <queue>\n#include <functional>\n#include <fstream>\n#include <iomanip>\n#include <utility>\n"
    linear.add(
        module,
        objective,
        title,
        theory,
        extra + declarations,
        body,
        wrong,
        right,
        before,
        after,
        changed_before,
        changed_after,
        variant,
        source,
    )


add(
    4,
    1,
    "朴素串匹配不能漏掉最后一个候选位置",
    "这里的匹配契约是返回首个零基起点，未找到返回 -1，空模式返回 0。只在完整模式仍落在文本内时比较；边界包含 i+m=n。",
    "",
    'string t="abababac",p=n==1?"ababac":"ab"; int answer=-1; for(int i=0;i+int(p.size())<int(t.size());++i){int j=0; while(j<int(p.size())&&t[i+j]==p[j])++j; if(j==int(p.size())){answer=i;break;}} cout<<answer<<\'\\n\';',
    "i+int(p.size())<int(t.size())",
    "i+int(p.size())<=int(t.size())",
    "-1\n",
    "2\n",
    "0\n",
    "0\n",
    "首位即可命中的短模式",
    "cornell-kmp",
)
add(
    4,
    2,
    "前缀回退不能把已有重叠全部丢弃",
    "本例 pi[i] 是 s[0..i] 的最长真前缀与后缀相同长度。失配时沿 pi[j-1] 继续回退，直到匹配或 j=0。它与讲义按前缀长度索引的 prefix[j] 相差一位，不能混用。",
    "",
    "string s=n==1?\"aabaaab\":\"abab\"; vector<int> pi(s.size()); for(int i=1;i<int(s.size());++i){int j=pi[i-1]; while(j>0&&s[i]!=s[j])j=0; if(s[i]==s[j])++j; pi[i]=j;} for(int x:pi)cout<<x<<' '; cout<<'\\n';",
    "j=0;",
    "j=pi[j-1];",
    "0 1 0 1 2 1 0 \n",
    "0 1 0 1 2 2 3 \n",
    "0 0 1 2 \n",
    "0 0 1 2 \n",
    "没有多次失配回退的交替模式",
    "cornell-kmp",
)
add(
    4,
    3,
    "稀疏坐标重复项按约定相加",
    "稀疏坐标保存行、列、值，未存坐标表示零。此例选择重复坐标求和的契约，与 COO 转换中的合并语义一致；覆盖写入不是同一契约。这里未实现广义表，不能据此认定该复合目标已完成。",
    "struct Term{int row,col,value;};",
    "vector<Term> terms{{0,0,3},{0,n==1?0:1,2}}; int dense[2][2]{}; for(auto x:terms)dense[x.row][x.col]=x.value; cout<<dense[0][0]<<' '<<dense[0][1]<<'\\n';",
    "dense[x.row][x.col]=x.value",
    "dense[x.row][x.col]+=x.value",
    "2 0\n",
    "5 0\n",
    "3 2\n",
    "3 2\n",
    "改为两个不同坐标",
    "scipy-coo",
)
add(
    5,
    1,
    "父节点表转换不能丢掉根的孩子",
    "父节点数组用 -1 表示根，非负下标表示父节点。转换为孩子列表时，下标 0 也是合法父节点。本例输入预先保证是树，非法父下标、多根与环仍需分别验证。",
    "",
    "vector<int> parent=n==1?vector<int>{-1,0,0,1}:vector<int>{-1,0}; vector<vector<int>> children(parent.size()); for(int i=0;i<int(parent.size());++i)if(parent[i]>0)children[parent[i]].push_back(i); cout<<children[0].size()<<' '<<children[1].size()<<'\\n';",
    "parent[i]>0",
    "parent[i]>=0",
    "0 1\n",
    "2 1\n",
    "0 0\n",
    "1 0\n",
    "只有根和一个孩子",
    "mit-trees",
)
add(
    5,
    2,
    "递归与迭代中序遍历应遵循同一顺序",
    "二叉树中序遍历为左子树、当前节点、右子树。递归调用栈与显式栈是两种实现；它们输出一致只验证本次结构，空树和偏斜树也要考虑。",
    "struct Node{int key;Node* left;Node* right;}; void walk(Node*p){if(!p)return; cout<<p->key<<' '; walk(p->left); walk(p->right);}",
    "Node l{1,nullptr,nullptr},r{3,nullptr,nullptr},root{2,&l,&r}; Node* p=n==1?&root:nullptr; walk(p); cout<<\"| \"; stack<Node*> st; while(p||!st.empty()){while(p){st.push(p);p=p->left;} p=st.top();st.pop();cout<<p->key<<' ';p=p->right;} cout<<'\\n';",
    "cout<<p->key<<' '; walk(p->left);",
    "walk(p->left); cout<<p->key<<' ';",
    "2 1 3 | 1 2 3 \n",
    "1 2 3 | 1 2 3 \n",
    "| \n",
    "| \n",
    "空树的两个实现都应终止",
    "mit-trees",
)
add(
    5,
    3,
    "Huffman 每次合并两个最小权重",
    "对给定正权重，Huffman 反复合并两个最小子树。各次合并权重之和等于最终叶子的加权路径长度；同权节点允许不同码字。此处比较代价，不强制唯一编码，也尚未核验码字前缀性质。",
    "",
    "vector<int> q=n==1?vector<int>{1,2,5}:vector<int>{1,1,1}; int cost=0; while(q.size()>1){sort(q.begin(),q.end(),greater<int>()); int sum=q[0]+q[1];q.erase(q.begin(),q.begin()+2);q.push_back(sum);cost+=sum;} cout<<cost<<'\\n';",
    "sort(q.begin(),q.end(),greater<int>())",
    "sort(q.begin(),q.end())",
    "15\n",
    "11\n",
    "5\n",
    "5\n",
    "三个相同权重，允许同权选择差异",
    "odsa-huffman",
)
add(
    6,
    1,
    "搜索树查找必须沿正确的比较方向",
    "这里二叉搜索树的键互异，左子树较小、右子树较大。查找由键比较决定方向；成功查找不证明插入、删除或整树有序性，这些条件须分别检查。",
    "struct Node{int key;Node*left;Node*right;}; bool contains(Node*p,int key){while(p){if(p->key==key)return true;p=key<p->key?p->right:p->left;}return false;}",
    "Node l{10,nullptr,nullptr},r{30,nullptr,nullptr},root{20,&l,&r};cout<<contains(&root,n==1?10:20)<<'\\n';",
    "key<p->key?p->right:p->left",
    "key<p->key?p->left:p->right",
    "0\n",
    "1\n",
    "1\n",
    "1\n",
    "根键命中不需要走分支",
    "mit-trees",
)
add(
    6,
    2,
    "旋转必须保留中间子树",
    "右旋将左孩子升为子树根，左孩子原右子树移交旧根的左链接，中序顺序应保持。这里只检查单次右旋的内容保留，不覆盖所有 AVL 平衡条件、双旋或删除回溯。",
    "struct Node{int key;Node*left;Node*right;}; void walk(Node*p){if(!p)return;walk(p->left);cout<<p->key<<' ';walk(p->right);}",
    "Node mid{25,nullptr,nullptr},b{20,nullptr,n==1?&mid:nullptr},a{30,&b,nullptr}; Node* top=&b; a.left=nullptr; b.right=&a; walk(top); cout<<'\\n';",
    "a.left=nullptr;",
    "a.left=b.right;",
    "20 30 \n",
    "20 25 30 \n",
    "20 30 \n",
    "20 30 \n",
    "中间子树为空时的旋转",
    "mit-avl",
)
add(
    6,
    3,
    "B+ 树叶分裂复制分隔键而非移走记录",
    "本例叶容量三，第四条记录使叶溢出；以右叶最小键作父分隔键，该记录仍留在右叶。内节点分裂的提升规则不同。本例只是受限页分裂工件，不是完整 B/B+ 树，尚未包含根传播、合并和范围扫描。",
    "",
    "vector<int> page=n==1?vector<int>{1,3,5,7}:vector<int>{1,3,5,7,9,11};int split=page.size()/2;int separator=page[split];vector<int> left(page.begin(),page.begin()+split),right(page.begin()+split+1,page.end());cout<<\"sep=\"<<separator<<\" left=\";for(int x:left)cout<<x<<' ';cout<<\"right=\";for(int x:right)cout<<x<<' ';cout<<'\\n';",
    "page.begin()+split+1",
    "page.begin()+split",
    "sep=5 left=1 3 right=7 \n",
    "sep=5 left=1 3 right=5 7 \n",
    "sep=7 left=1 3 5 right=9 11 \n",
    "sep=7 left=1 3 5 right=7 9 11 \n",
    "容量五的叶溢出，分隔键仍保留",
    "cmu-bplus",
)
add(
    7,
    1,
    "无向边在邻接表中登记两个方向",
    "有向边只登记起点的出邻接，无向边在两端邻接表登记。输入中的图类型决定存储行为；两个邻接项表示同一条无向边，而非两条不同边。",
    "",
    "vector<vector<int>> adj(2);adj[0].push_back(1);cout<<adj[0].size()<<' '<<adj[1].size()<<'\\n';",
    "adj[0].push_back(1);",
    "adj[0].push_back(1);if(n==1)adj[1].push_back(0);",
    "1 0\n",
    "1 1\n",
    "1 0\n",
    "1 0\n",
    "换为有向图，不应添加反向边",
    "mit-bfs",
)
add(
    7,
    2,
    "BFS 入队时登记已发现节点",
    "本例以固定邻接顺序展示 BFS。入队时登记已发现可避免同一个节点由多个前驱重复加入队列；合法访问顺序可能不唯一。这里只检查给定工件的规范轨迹，不将另一合法顺序判为算法错误。DFS 另需实践。",
    "",
    "vector<vector<int>> adj=n==1?vector<vector<int>>{{1,2},{3},{3},{}}:vector<vector<int>>{{1},{2},{3},{}};vector<bool> seen(4);queue<int> q;q.push(0);seen[0]=true;while(!q.empty()){int u=q.front();q.pop();cout<<u<<' ';for(int v:adj[u])if(!seen[v]){q.push(v);}}cout<<'\\n';",
    "q.push(v);",
    "seen[v]=true;q.push(v);",
    "0 1 2 3 3 \n",
    "0 1 2 3 \n",
    "0 1 2 3 \n",
    "0 1 2 3 \n",
    "单一路径不会暴露重复入队错误",
    "mit-bfs",
)
add(
    7,
    3,
    "遍历整图必须重新启动未访问的分量",
    "从一个起点搜索只保证覆盖可达部分。无向图的每个连通分量需单独启动搜索，孤立顶点也算一个分量；搜索森林每个分量贡献一棵树。这里不求最小生成树。",
    "",
    "vector<vector<int>> adj=n==1?vector<vector<int>>{{1},{0},{},{}}:vector<vector<int>>{{1},{0,2},{1,3},{2}};vector<bool> seen(4);int components=0;for(int start=0;start<4;++start){if(seen[start])continue;++components;queue<int> q;q.push(start);seen[start]=true;while(!q.empty()){int u=q.front();q.pop();for(int v:adj[u])if(!seen[v]){seen[v]=true;q.push(v);}}break;}cout<<components<<'\\n';",
    "}break;",
    "}",
    "1\n",
    "3\n",
    "1\n",
    "1\n",
    "改为一个连通分量",
    "mit-dfs",
)
add(
    8,
    1,
    "最短路松弛使用整条已知路径代价",
    "松弛候选为 d[u]+w(u,v)，并与当前 d[v] 比较。本例用数组选择当前最小未访问距离实现非负权 Dijkstra；固定小图不构成复杂度或负权适用性证明。不可达项不能当成零。",
    "",
    "const int INF=100000;int w[3][3]={{INF,n==1?2:0,9},{INF,INF,3},{INF,INF,INF}};array<int,3>d{0,INF,INF};array<bool,3> used{};for(int k=0;k<3;++k){int u=-1;for(int v=0;v<3;++v)if(!used[v]&&(u==-1||d[v]<d[u]))u=v;if(u==-1||d[u]==INF)break;used[u]=true;for(int v=0;v<3;++v)if(w[u][v]!=INF)d[v]=min(d[v],w[u][v]);}cout<<d[2]<<'\\n';",
    "min(d[v],w[u][v])",
    "min(d[v],d[u]+w[u][v])",
    "3\n",
    "5\n",
    "3\n",
    "3\n",
    "首条边权为零，仍符合适用前提",
    "mit-dijkstra",
)
add(
    8,
    2,
    "拓扑排序必须报告环导致的未完成",
    "Kahn 算法从入度零节点推进。取出的节点数不足声明顶点数时存在环，不能报告完整拓扑序。DAG 可能有多个合法序，本工件只比较完成数量与是否有环。",
    "",
    "vector<vector<int>> adj=n==1?vector<vector<int>>{{1},{2},{0}}:vector<vector<int>>{{1},{2},{}};array<int,3> degree{};for(auto row:adj)for(int v:row)++degree[v];queue<int>q;for(int v=0;v<3;++v)if(degree[v]==0)q.push(v);int count=0;while(!q.empty()){int u=q.front();q.pop();++count;for(int v:adj[u])if(--degree[v]==0)q.push(v);}cout<<\"dag \"<<count<<'\\n';",
    'cout<<"dag "',
    'cout<<(count==3?"dag ":"cycle ")',
    "dag 0\n",
    "cycle 0\n",
    "dag 3\n",
    "dag 3\n",
    "移除回边后能够完成全部节点",
    "mit-dfs",
)
add(
    8,
    3,
    "事件最早发生时间取所有前驱约束的最大值",
    "在活动置于边上的 DAG 中，事件须等待全部前驱活动完成，因此最早时间采用最长路径递推，不是最短路。此例事件已经按拓扑次序编号，非负活动时长；尚未检查有环拒绝、最晚时间与全部关键活动。",
    "struct Edge{int u,v,w;};",
    "vector<Edge> edges{{0,1,n==1?2:0},{0,2,n==1?5:0},{1,3,n==1?4:0},{2,3,n==1?3:0}};array<int,4> earliest{};for(int u=0;u<4;++u)for(auto e:edges)if(e.u==u)earliest[e.v]=min(earliest[e.v],earliest[u]+e.w);cout<<earliest[3]<<'\\n';",
    "min(earliest[e.v],earliest[u]+e.w)",
    "max(earliest[e.v],earliest[u]+e.w)",
    "0\n",
    "8\n",
    "0\n",
    "0\n",
    "所有活动时长为零，完工时间允许为零",
    "gordon-cpm",
)
add(
    9,
    1,
    "散列下标需要落在有效槽范围",
    "此任务允许负整数键，容量五；将 C++ 余数规范到 [0,5) 后才访问数组。合法下标不代表良好哈希分布；本任务也没有覆盖全部查找或重散列行为。",
    "",
    "int key=n==1?-1:6;int index=key%5;array<int,5> table{};if(index<0||index>=5){cout<<\"bad-index\\n\";return 0;}table[index]=77;cout<<table[index]<<'\\n';",
    "int index=key%5;",
    "int index=(key%5+5)%5;",
    "bad-index\n",
    "77\n",
    "77\n",
    "77\n",
    "正整数键的原路径仍应可用",
    "cpp17-draft",
)
add(
    9,
    2,
    "墓碑不能截断线性探查链",
    "开放寻址中从未使用的空槽与删除后的墓碑是不同状态。遇墓碑继续探查，否则同一探查链后续键被错误报告缺失。本例容量三、-1 为空、-2 为墓碑，键限制为非负。",
    "",
    "array<int,3> table{n==1?-2:3,6,-1};int key=6,found=-1;for(int step=0;step<3;++step){int slot=(key%3+step)%3;if(table[slot]<0)break;if(table[slot]==key){found=slot;break;}}cout<<found<<'\\n';",
    "table[slot]<0",
    "table[slot]==-1",
    "-1\n",
    "1\n",
    "1\n",
    "1\n",
    "未删除的碰撞链仍需正确查找",
    "odsa-hash-delete",
)
add(
    9,
    3,
    "装载率不能用整数除法计算",
    "装载率定义为存储键数除以槽数。它是表示状态的指标，并不能单独证明某种碰撞策略的代价；还需比较探查长度与键分布。本例先纠正指标的整数截断。",
    "",
    "int keys=n==1?3:5,capacity=5;double load=keys/capacity;cout<<fixed<<setprecision(3)<<load<<'\\n';",
    "double load=keys/capacity;",
    "double load=double(keys)/capacity;",
    "0.000\n",
    "0.600\n",
    "1.000\n",
    "1.000\n",
    "装载率等于一仍不是性能保证",
    "mit-hash",
)
add(
    10,
    1,
    "插入排序必须允许搬移首元素",
    "插入排序将当前键插入已排序前缀，搬移条件必须包含下标零。排序结果应有序且保留原多重集合；本例固定三个元素，不覆盖其他内部排序算法。",
    "",
    "vector<int>a=n==1?vector<int>{3,1,2}:vector<int>{1,2,3};for(int i=1;i<int(a.size());++i){int key=a[i],j=i-1;while(j>0&&a[j]>key){a[j+1]=a[j];--j;}a[j+1]=key;}for(int x:a)cout<<x<<' ';cout<<'\\n';",
    "j>0&&",
    "j>=0&&",
    "3 1 2 \n",
    "1 2 3 \n",
    "1 2 3 \n",
    "1 2 3 \n",
    "已排序输入不能暴露遗漏首元素的错误",
    "mit-sort",
)
add(
    10,
    2,
    "稳定排序保留同键记录的原相对顺序",
    "按键排序时，稳定性保留同键记录原先的先后。插入排序若把相等键也向右搬移会逆转它们；不同键的输入无法验证稳定性。本例未证明所有排序算法的复杂度。",
    "",
    "vector<pair<int,char>>a{{2,'A'},{n==1?2:3,'B'},{1,'C'}};for(int i=1;i<int(a.size());++i){auto key=a[i];int j=i-1;while(j>=0&&a[j].first>=key.first){a[j+1]=a[j];--j;}a[j+1]=key;}for(auto x:a)cout<<x.first<<x.second<<' ';cout<<'\\n';",
    "a[j].first>=key.first",
    "a[j].first>key.first",
    "1C 2B 2A \n",
    "1C 2A 2B \n",
    "1C 2A 3B \n",
    "1C 2A 3B \n",
    "全部键不同不能作为稳定性证据",
    "mit-sort",
)
add(
    10,
    3,
    "磁盘有序段需要归并而非直接拼接",
    "外部排序先生成有序段，再按内存约束归并。此例在隔离环境真实写入两个小段，归并时各保留一个当前记录；文件只在本次执行存在，尚未验证大文件、I/O 故障、多轮归并或完整目录导航项目。",
    "",
    "vector<int>a{4,1},b=n==1?vector<int>{3,2}:vector<int>{5,6};sort(a.begin(),a.end());sort(b.begin(),b.end());{ofstream f(\"run-a.txt\"),g(\"run-b.txt\");for(int x:a)f<<x<<'\\n';for(int x:b)g<<x<<'\\n';}ifstream f(\"run-a.txt\"),g(\"run-b.txt\");int x,y;bool hasX=bool(f>>x),hasY=bool(g>>y);while(hasX||hasY){if(hasX){cout<<x<<' ';hasX=bool(f>>x);}else{cout<<y<<' ';hasY=bool(g>>y);}}cout<<'\\n';",
    "if(hasX){",
    "if(hasX&&(!hasY||x<=y)){",
    "1 4 2 3 \n",
    "1 2 3 4 \n",
    "1 4 5 6 \n",
    "1 4 5 6 \n",
    "两段键范围不重叠时拼接碰巧有序",
    "odsa-external",
)

if __name__ == "__main__":
    edges = [
        (
            "M01-O01",
            "M01-O02",
            "conceptual_association",
            linear.SOURCE,
            "契约与存储表示是两个不同层次。",
        ),
        (
            "M01-O02",
            "M02-O01",
            "application",
            linear.SOURCE,
            "连续存储对应顺序表元素搬移。",
        ),
        (
            "M01-O03",
            "M10-O01",
            "application",
            "mit-sort",
            "比较与搬移计数用于分析内部排序代价。",
        ),
        (
            "M02-O02",
            "M02-O03",
            "conceptual_association",
            linear.SOURCE,
            "单向和双向链接分别检查后继与前驱。",
        ),
        (
            "M02-O02",
            "M03-O02",
            "application",
            linear.SOURCE,
            "链接操作用于链式队列；当前实践深度尚未覆盖链式队列。",
        ),
        (
            "M03-O01",
            "M03-O03",
            "application",
            linear.SOURCE,
            "后进先出结构用于记录未闭合括号。",
        ),
        (
            "M03-O02",
            "M07-O02",
            "application",
            "mit-bfs",
            "先进先出队列用于 BFS 逐层推进。",
        ),
        (
            "M04-O01",
            "M04-O02",
            "conceptual_association",
            "cornell-kmp",
            "朴素匹配与前缀回退处理同一匹配接口。",
        ),
        (
            "M04-O03",
            "M07-O01",
            "conceptual_association",
            "mit-bfs",
            "稀疏坐标与邻接表示都需要定义未存项的语义。",
        ),
        ("M05-O01", "M05-O02", "application", "mit-trees", "遍历应用于节点链接表示。"),
        (
            "M05-O02",
            "M06-O01",
            "conceptual_association",
            "mit-trees",
            "中序有序性用于检查搜索树；遍历不是唯一查找实现，未设严格先修。",
        ),
        (
            "M05-O03",
            "M05-O01",
            "application",
            "odsa-huffman",
            "Huffman 合并产物可以表示为带权二叉树。",
        ),
        (
            "M06-O01",
            "M06-O02",
            "application",
            "mit-avl",
            "旋转须保持搜索树有序性与子树内容。",
        ),
        (
            "M06-O03",
            "M10-O03",
            "conceptual_association",
            "cmu-bplus",
            "页容量与外部存储访问影响索引及排序选择。",
        ),
        (
            "M07-O02",
            "M07-O03",
            "application",
            "mit-dfs",
            "重复启动搜索用于覆盖各连通分量。",
        ),
        (
            "M07-O02",
            "M08-O01",
            "conceptual_association",
            "mit-dijkstra",
            "无权逐层距离与带权最短路的适用条件不同。",
        ),
        (
            "M07-O02",
            "M08-O02",
            "application",
            "mit-dfs",
            "图遍历可用于拓扑排序，但不是唯一实现。",
        ),
        (
            "M08-O02",
            "M08-O03",
            "application",
            "gordon-cpm",
            "拓扑次序用于 DAG 事件时间的递推。",
        ),
        (
            "M09-O01",
            "M09-O02",
            "application",
            "mit-hash",
            "同槽冲突需要定义完整探查与删除状态语义。",
        ),
        (
            "M09-O02",
            "M09-O03",
            "conceptual_association",
            "mit-hash",
            "装载率和删除状态共同影响探查工作量。",
        ),
        (
            "M10-O01",
            "M10-O02",
            "application",
            "mit-sort",
            "排序移动规则决定同键稳定性。",
        ),
        (
            "M10-O01",
            "M10-O03",
            "application",
            "odsa-external",
            "内部排序生成有序段用于外部归并。",
        ),
    ]
    for start, end, kind, source, reason in edges:
        book.package["relations"].append(
            {
                "from": "CS03-" + start,
                "to": "CS03-" + end,
                "kind": kind,
                "reason": reason,
                "source_locator": source,
                "course_version_id": book.version,
                "review_state": "authority_checked",
                "source": "原创教学工件关联："
                + reason
                + " 机制参见 "
                + source
                + "；专业审校不可用。",
            }
        )
    book.save("CS03-core")
