"""Original bounded AI algorithm counterexamples with explicit assumptions."""

from pathlib import Path

from code_authoring import CodeBook

ROOT = Path(__file__).resolve().parents[2]
book = CodeBook(
    ROOT,
    "CS12-core-scope-0.1.0",
    "CS12-core-practice-0.1.0",
    "原创有限搜索、约束、推理、概率与计划活动；完整问题求解系统及独立迁移待建设。",
    course="CS12",
    standard="code-fixed-condition-v1",
)
SOURCES = [
    (
        "ai-search",
        "Berkeley Informed Search",
        "https://inst.eecs.berkeley.edu/~cs188/textbook/search/informed.html",
        "cost, heuristic and A star",
    ),
    (
        "ai-pruning",
        "Poole and Mackworth Pruning",
        "https://artint.info/3e/html/ArtInt3e.Ch3.S7.html",
        "cycle and multiple-path pruning",
    ),
    (
        "ai-filter",
        "Berkeley CSP Filtering",
        "https://inst.eecs.berkeley.edu/~cs188/textbook/csp/filtering.html",
        "support and arc revision",
    ),
    (
        "ai-local",
        "Berkeley Local Search",
        "https://inst.eecs.berkeley.edu/~cs188/textbook/search/local.html",
        "local optima and search limitations",
    ),
    (
        "ai-csp",
        "Berkeley CSP Solving",
        "https://inst.eecs.berkeley.edu/~cs188/textbook/csp/solving.html",
        "backtracking and constraint checking",
    ),
    (
        "ai-game",
        "Berkeley Minimax",
        "https://inst.eecs.berkeley.edu/~cs188/textbook/games/minimax.html",
        "adversarial alternating value",
    ),
    (
        "ai-logic",
        "Poole and Mackworth Definite Clauses",
        "https://artint.info/3e/html/ArtInt3e.Ch5.S3.html",
        "positive Horn inference; signed facts are original extension",
    ),
    (
        "ai-prob",
        "Berkeley Probability Inference",
        "https://inst.eecs.berkeley.edu/~cs188/textbook/bayes-nets/inference.html",
        "enumeration, marginalization and normalization",
    ),
    (
        "ai-plan",
        "Poole and Mackworth Planning",
        "https://artint.info/3e/html/ArtInt3e.Ch6.S1.html",
        "preconditions and effects",
    ),
]
book.package["sources"] = [
    {
        "id": k,
        "title": t,
        "url": u,
        "locator": l,
        "checked_at": "2026-10-10",
        "status": "authority_checked",
    }
    for k, t, u, l in SOURCES
]
book.package["activities"] = []


def add(
    module,
    objective,
    title,
    theory,
    source,
    code,
    wrong,
    right,
    before,
    after,
    changed_before,
    changed_after,
    variant,
):
    goal = f"CS12-M{module:02d}-O{objective:02d}"
    initial = "n = int(input())\n" + code.strip() + "\n"
    assert wrong in initial, goal
    repaired = initial.replace(wrong, right)
    cases = []
    for task, label, stdin, first, second in [
        ("base", title, "1\n", before, after),
        ("changed-condition", variant, "2\n", changed_before, changed_after),
    ]:
        request = {
            "language": "python313",
            "entry": "main.py",
            "files": {"main.py": initial},
            "stdin": stdin,
        }
        answer = {**request, "files": {"main.py": repaired}}
        cases.append(
            (
                task,
                label,
                "先写输入约束及预测，运行并保存反例，修改后解释哪些结论尚未证明。",
                request,
                answer,
                first,
                second,
            )
        )
    book.add(
        goal,
        title,
        "标注契约与证据，再用实际运行定位违反条件的步骤。",
        [
            theory,
            "本例的固定运行只支持列出的观察；证明、一般界和独立迁移不由输出代替。",
        ],
        [
            "先区分输出错误、输入前提变化和论证缺口。",
            "检查最小反例与边界，并解释修改依据。",
        ],
        [source],
        cases,
    )


CASES = [
    (
        1,
        1,
        "状态键不能漏掉钥匙信息",
        "原创门禁路径，位置相同但钥匙状态不同决定后续可行动作。",
        "ai-search",
        "a=(0,False);b=(0,n==1)\nprint(a[0]==b[0])",
        "a[0]==b[0]",
        "a==b",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "钥匙状态也相同",
    ),
    (
        1,
        2,
        "路径评价应累加各边代价",
        "原创路径边权均非负，不以边数代替总代价。",
        "ai-search",
        "costs=[2,8] if n==1 else [1,1]\nprint(len(costs))",
        "len(costs)",
        "sum(costs)",
        "2\n",
        "10\n",
        "2\n",
        "2\n",
        "单位边权",
    ),
    (
        1,
        3,
        "不可观测状态不能假定已知",
        "原创机器人信念集包含左/右两位置，观测未知时保留候选，不伪造真实位置。",
        "ai-search",
        "belief={'left','right'} if n==1 else {'left'}\nprint('left')",
        "print('left')",
        "print(' '.join(sorted(belief)))",
        "left\n",
        "left right\n",
        "left\n",
        "left\n",
        "确定位置",
    ),
    (
        2,
        1,
        "BFS的队列不能当DFS栈使用",
        "原创有限无权图S直接邻居G，同时A继续到B；队列选先入，比较访问轨迹不证明全部算法。",
        "ai-pruning",
        "graph={'S':['G','A'],'A':['B'],'B':[],'G':[]} if n==1 else {'S':['G'],'G':[]}\nqueue=['S'];seen={'S'};order=[]\nwhile queue:\n v=queue.pop();order.append(v)\n if v=='G':break\n for w in graph[v]:\n  if w not in seen:seen.add(w);queue.append(w)\nprint(' '.join(order))",
        "queue.pop()",
        "queue.pop(0)",
        "S A B G\n",
        "S G\n",
        "S G\n",
        "S G\n",
        "无分支图",
    ),
    (
        2,
        2,
        "有界DFS未找到不证明目标不存在",
        "原创无限链模型只探索预算内前缀，目标在预算外时结果应为未知，而非不存在。",
        "ai-pruning",
        "limit=3;goal=5 if n==1 else 2\nfound=goal<limit\nprint('found' if found else 'absent')",
        "'absent'",
        "'unknown:budget'",
        "absent\n",
        "unknown:budget\n",
        "found\n",
        "found\n",
        "目标位于预算内",
    ),
    (
        2,
        3,
        "搜索峰值前沿不能以当前大小代替",
        "实际队列大小轨迹给定2、5、1，空间观察应取峰值；节点字节和算法一般界另需说明。",
        "ai-search",
        "sizes=[2,5,1] if n==1 else [1,2,3]\nprint(sizes[-1])",
        "sizes[-1]",
        "max(sizes)",
        "1\n",
        "5\n",
        "3\n",
        "3\n",
        "递增前沿",
    ),
    (
        3,
        1,
        "启发距离不得超过已知最短代价",
        "原创有限图给定真实最短代价2，h=3过估计；此核对只支持所列节点，不证明全部状态可采纳。",
        "ai-search",
        "distance=2;h=3 if n==1 else 1\nprint(h>=0)",
        "h>=0",
        "0<=h<=distance",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "低估启发值",
    ),
    (
        3,
        2,
        "一致性必须核对边上的三角条件",
        "原创边u到v代价1，h(u)=3,h(v)=1不一致；非负启发不自动一致。",
        "ai-search",
        "cost=1;hu=3 if n==1 else 2;hv=1\nprint(hu>=0 and hv>=0)",
        "hu>=0 and hv>=0",
        "hu<=cost+hv",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "满足边约束",
    ),
    (
        3,
        3,
        "A星必须按g加h而非只按h扩展",
        "真实堆搜索有限非负图：S到G代价5/S到A1/A到G1，可采纳一致h(A)=1；弹出目标时结束。",
        "ai-search",
        "import heapq\ngraph={'S':[('G',5),('A',1)],'A':[('G',1)],'G':[]}\nif n==2:graph['S']=[('G',1)]\nh={'S':0,'A':1,'G':0};front=[(0,0,'S')];best={'S':0}\nwhile front:\n _,g,v=heapq.heappop(front)\n if g!=best[v]:continue\n if v=='G':print(g);break\n for w,c in graph[v]:\n  ng=g+c\n  if ng<best.get(w,float('inf')):best[w]=ng;heapq.heappush(front,(h[w],ng,w))",
        "(h[w],ng,w)",
        "(ng+h[w],ng,w)",
        "5\n",
        "2\n",
        "1\n",
        "1\n",
        "仅直达边",
    ),
    (
        4,
        1,
        "对手节点在minimax中选择最小值",
        "原创深度二零和完全信息树，根max、下一层min；不默认对手帮助我方。",
        "ai-game",
        "branches=[[3,1],[2,2]] if n==1 else [[1,1],[2,2]]\nprint(max(max(row) for row in branches))",
        "max(max(row) for row in branches)",
        "max(min(row) for row in branches)",
        "3\n",
        "2\n",
        "2\n",
        "2\n",
        "分支结果相同",
    ),
    (
        4,
        2,
        "局部极值停止不代表全局最优",
        "原创目标序列1、3、2、5，严格爬山在3停；保存局部与枚举全局对照，不宣称重启一定全局。",
        "ai-local",
        "values=[1,3,2,5] if n==1 else [1,2,3]\ni=0\nwhile i+1<len(values) and values[i+1]>values[i]:i+=1\nprint(values[i]==max(values))",
        "print(values[i]==max(values))",
        "print(str(values[i])+' '+str(max(values)))",
        "False\n",
        "3 5\n",
        "True\n",
        "3 3\n",
        "单调目标",
    ),
    (
        4,
        3,
        "相同解值还需比较展开代价",
        "原创两个已验证解值相同的记录，比较访问计数；不是实际alpha-beta实现性能测量。",
        "ai-game",
        "value={'plain':2,'pruned':2};nodes={'plain':7,'pruned':5 if n==1 else 7}\nprint(value['plain']==value['pruned'])",
        "print(value['plain']==value['pruned'])",
        "print(value['plain']==value['pruned'],nodes['plain']-nodes['pruned'])",
        "True\n",
        "True 2\n",
        "True\n",
        "True 0\n",
        "无剪枝收益",
    ),
    (
        5,
        1,
        "CSP赋值必须同时满足域与约束",
        "原创X,Y域1/2且不等，域内赋值仍可能冲突。",
        "ai-csp",
        "x=1;y=1 if n==1 else 2\nprint(x in {1,2} and y in {1,2})",
        "x in {1,2} and y in {1,2}",
        "x in {1,2} and y in {1,2} and x!=y",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "有效不等赋值",
    ),
    (
        5,
        2,
        "弧修正删除没有支持的值",
        "原创X!=Y，Y域仅1时X值1无支持；只做一次弧修正，不称完整AC3。",
        "ai-filter",
        "dx={1,2};dy={1} if n==1 else {1,2}\nprint(' '.join(map(str,sorted(dx))))",
        "sorted(dx)",
        "sorted(x for x in dx if any(x!=y for y in dy))",
        "1 2\n",
        "2\n",
        "1 2\n",
        "1 2\n",
        "两个值均有支持",
    ),
    (
        5,
        3,
        "空域必须报告不满足而非选默认值",
        "原创X!=Y且两域仅1无解；完整枚举有限两变量，不能硬写默认赋值。",
        "ai-csp",
        "dx=[1];dy=[1] if n==1 else [2]\nsolutions=[(x,y) for x in dx for y in dy if x!=y]\nprint('1 1')",
        "print('1 1')",
        "print('unsat' if not solutions else ' '.join(map(str,solutions[0])))",
        "1 1\n",
        "unsat\n",
        "1 1\n",
        "1 2\n",
        "存在解",
    ),
    (
        6,
        1,
        "未知事实不能自动作假",
        "原创开放世界事实查询：未登记不是已证伪，正负事实分别存储。",
        "ai-logic",
        "positive={'ready'};negative=set();fact='door' if n==1 else 'ready'\nprint(fact in positive)",
        "print(fact in positive)",
        "print('true' if fact in positive else 'false' if fact in negative else 'unknown')",
        "False\n",
        "unknown\n",
        "True\n",
        "true\n",
        "明确已知事实",
    ),
    (
        6,
        2,
        "前向链须迭代到固定点",
        "原创正Horn规则b到c排在a到b前，单轮会漏c；有限事实闭包可终止。",
        "ai-logic",
        "facts={'a'} if n==1 else {'b'}\nrules=[({'b'},'c'),({'a'},'b')]\nfor pre,out in rules:\n if pre<=facts:facts.add(out)\nprint(' '.join(sorted(facts)))",
        "for pre,out in rules:\n if pre<=facts:facts.add(out)",
        "while True:\n before=set(facts)\n for pre,out in rules:\n  if pre<=facts:facts.add(out)\n if before==facts:break",
        "a b\n",
        "a b c\n",
        "b c\n",
        "b c\n",
        "从中间事实起步",
    ),
    (
        6,
        3,
        "显式正负冲突不能被忽略",
        "原创带符号事实仓库需报告同一事实正负同时出现；这是冲突检查策略，不称完整非单调逻辑。",
        "ai-logic",
        "positive={'ready'};negative={'ready'} if n==1 else {'locked'}\nprint('consistent')",
        "print('consistent')",
        "print('conflict' if positive&negative else 'consistent')",
        "consistent\n",
        "conflict\n",
        "consistent\n",
        "consistent\n",
        "没有相反事实",
    ),
    (
        7,
        1,
        "条件概率需要除以证据概率",
        "原创联合概率P(A且B)=1/8、P(B)=1/4，P(A|B)=1/2；分母零不能定义普通条件概率。",
        "ai-prob",
        "from fractions import Fraction\njoint=Fraction(1,8);evidence=Fraction(1,4) if n==1 else Fraction(1)\nprint(joint)",
        "print(joint)",
        "print(joint/evidence)",
        "1/8\n",
        "1/2\n",
        "1/8\n",
        "1/8\n",
        "证据概率为一",
    ),
    (
        7,
        2,
        "贝叶斯网络边缘化要包含全部父值",
        "原创二值A到B，P(A)=1/2，P(B|A)=3/4，P(B|非A)=1/4，结果1/2；不能只算A真项。",
        "ai-prob",
        "from fractions import Fraction\np=Fraction(1,2) if n==1 else Fraction(1);yes=Fraction(3,4);no=Fraction(1,4)\nprint(p*yes)",
        "p*yes",
        "p*yes+(1-p)*no",
        "3/8\n",
        "1/2\n",
        "3/4\n",
        "3/4\n",
        "父变量总为真",
    ),
    (
        7,
        3,
        "独立性假设需用联合表核对",
        "原创二值联合表对角各1/2，边缘各1/2但联合1/2不等1/4；单对值可否定却不能证明全表独立。",
        "ai-prob",
        "from fractions import Fraction\npa=pb=Fraction(1,2);joint=Fraction(1,2) if n==1 else Fraction(1,4)\nprint(pa==pb)",
        "pa==pb",
        "joint==pa*pb",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "这一个格满足分解",
    ),
    (
        8,
        1,
        "动作不满足前提不能执行效果",
        "原创开门动作需要key，未满足时返回原状态并报告blocked。",
        "ai-plan",
        "state={'key'} if n==2 else set();pre={'key'}\nstate.add('open');print(' '.join(sorted(state)))",
        "state.add('open');print(' '.join(sorted(state)))",
        "if pre<=state:state.add('open');print(' '.join(sorted(state)))\nelse:print('blocked')",
        "open\n",
        "blocked\n",
        "key open\n",
        "key open\n",
        "前提已满足",
    ),
    (
        8,
        2,
        "计划回放必须逐步检查前提与目标",
        "原创取钥匙再开门计划，逆序执行失败；不能只因动作名单含open就视为计划成功。",
        "ai-plan",
        "plan=['open','take'] if n==1 else ['take','open'];state=set()\nprint('open' in plan)",
        "print('open' in plan)",
        "valid=True\nfor action in plan:\n if action=='take':state.add('key')\n elif 'key' in state:state.add('open')\n else:valid=False;break\nprint(valid and 'open' in state)",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "合法动作次序",
    ),
    (
        8,
        3,
        "奖励反馈不能当监督标签",
        "原创记录以显式signal_kind标识监督label或强化reward，不根据数值0/1猜任务。",
        "ai-plan",
        "record={'value':1,'signal_kind':'reward' if n==1 else 'label'}\nprint('supervised')",
        "print('supervised')",
        "print('reinforcement' if record['signal_kind']=='reward' else 'supervised')",
        "supervised\n",
        "reinforcement\n",
        "supervised\n",
        "supervised\n",
        "监督标签记录",
    ),
    (
        9,
        1,
        "相同成功数下仍须比较资源预算",
        "原创固定评估记录成功数相同，模型预算按给定成本排序；不声称真实平台模型测评。",
        "ai-search",
        "cost={'A':8,'B':2 if n==1 else 8}\nprint('A')",
        "print('A')",
        "print(min(cost,key=lambda k:(cost[k],k)))",
        "A\n",
        "B\n",
        "A\n",
        "A\n",
        "成本相同按名称稳定选择",
    ),
    (
        9,
        2,
        "总准确率不能掩盖组间误差",
        "原创固定评估A组9/10，B组1/2；这是描述性组差异，不证明歧视原因或完整公平性。",
        "ai-prob",
        "from fractions import Fraction\na=Fraction(9,10);b=Fraction(1,2) if n==1 else Fraction(9,10)\nprint(a==a)",
        "a==a",
        "a==b",
        "True\n",
        "False\n",
        "True\n",
        "True\n",
        "两组正确率相同",
    ),
    (
        9,
        3,
        "应用边界需处理分布外输入",
        "原创规则只支持整数0到10，超范围应拒绝自动结论并保留核验；拒绝不证明全部安全性。",
        "ai-plan",
        "value=20 if n==1 else 5\nprint('automatic')",
        "print('automatic')",
        "print('automatic' if type(value) is int and 0<=value<=10 else 'needs_review')",
        "automatic\n",
        "needs_review\n",
        "automatic\n",
        "automatic\n",
        "声明范围内输入",
    ),
]
for row in CASES:
    add(*row)
if __name__ == "__main__":
    book.package["relations"] = []
    for module in range(1, 10):
        for left, right in [(1, 2), (2, 3)]:
            book.package["relations"].append(
                {
                    "from": f"CS12-M{module:02d}-O{left:02d}",
                    "to": f"CS12-M{module:02d}-O{right:02d}",
                    "kind": "conceptual_association",
                    "reason": "条件对照："
                    + CASES[(module - 1) * 3 + left - 1][2]
                    + "与"
                    + CASES[(module - 1) * 3 + right - 1][2],
                    "source_locator": CASES[(module - 1) * 3 + right - 1][4],
                    "course_version_id": book.version,
                    "review_state": "authority_checked",
                    "source": "原创算法工件关联，非教学顺序生成严格先修；专业审校不可用。",
                }
            )
    book.save("CS12-core")
