import { useState } from 'react'
import { Link, useSearchParams } from 'react-router-dom'
import { courses, COURSE_VERSION, TRACE_OBJECTIVE, IMPLEMENT_OBJECTIVE, currentTraceEvidence, evidenceState, stateLabels, objectiveSummary } from '../domain/learning'
import { useLocal } from '../local/LocalProvider'
import KnowledgeGraph from './KnowledgeGraph'

export default function Atlas() {
  const [params, setParams] = useSearchParams()
  const course = courses.find(course => course.code === params.get('course')) ?? courses[2]
  const [selected, setSelected] = useState(TRACE_OBJECTIVE)
  const { evidence } = useLocal()
  const state = evidenceState(currentTraceEvidence(evidence)?.result)
  const summary = objectiveSummary(evidence)
  const available = course.code === 'CS03'
  return <div className="page atlas-page"><div className="page-topline"><span className="eyebrow">KNOWLEDGE / ATLAS</span><label className="course-picker">课程 <select value={course.code} onChange={event => setParams({ course: event.target.value })}>{courses.map(course => <option key={course.code} value={course.code}>{course.title}</option>)}</select></label></div><div className="page-heading"><div><h1>{course.title}<span className="heading-note">知识图谱</span></h1><p>{available ? '在知识之间定位，用作品辨认你走过的路。' : course.description}</p></div>{available && <div className="scope-total"><strong>{summary.verified}<span> / 2</span></strong><span>样例目标有达标证据</span></div>}</div>
    {!available ? <section className="construction-state"><span className="large-orbit" aria-hidden="true">◌</span><div className="eyebrow">正在建设完整内容</div><h2>这门课的默认图谱还没有开放</h2><p>完整的理论、实践与核验内容尚未建成。你现在可以用自己的目标建立个人课程，保留学习尝试；自建内容会标为未审校、未核验。</p><Link className="button primary" to="/my-courses">建立个人课程 <span aria-hidden="true">↗</span></Link><Link className="text-link" to="/atlas?course=CS03">先试栈单元工程样例 →</Link></section> : <>
      <div className="scope-note"><span className="small-tag">局部工程样例</span><p>已定义范围：线性结构 → 栈及括号匹配，2 个目标。完整课程尚在建设；此处比例仅描述样例证据。内容、先修和标准待教学审校。</p></div>
      <section className="atlas-body"><div className="atlas-map"><KnowledgeGraph state={state} selected={selected} onSelect={setSelected}/><div className="graph-legend"><span><i className="legend-dot unknown"/>尚未有效评估</span><span><i className="legend-dot partial"/>部分条件满足</span><span><i className="legend-dot consolidate"/>需巩固</span><span><i className="legend-dot verified"/>有达标证据</span></div><div className="graph-relation">实线：章节与目标归属　 ·　虚线箭头：先修关系（内容审阅待完成）</div></div><aside className="objective-inspector"><span className="eyebrow">当前目标 / {selected === TRACE_OBJECTIVE ? '01' : '02'}</span><h2>{selected === TRACE_OBJECTIVE ? '让栈的每一步，变得清楚。' : '用栈，识别成对的括号。'}</h2><span className={`evidence-pill ${selected === TRACE_OBJECTIVE ? state : 'unknown'}`}>{stateLabels[selected === TRACE_OBJECTIVE ? state : 'unknown']}</span><h3>需要留下的表现</h3><ul className="criteria-list">{selected === TRACE_OBJECTIVE ? <><li>逐步推演入栈、出栈与输出</li><li>明确空栈出栈的处理约定</li><li>解释后进先出，并在新条件中独立应用</li></> : <><li>匹配最近尚未闭合的同种左括号</li><li>处理多余闭括号、类型不匹配与残留左括号</li><li>保留源码、边界测试与独立解释</li></>}</ul>{selected === IMPLEMENT_OBJECTIVE && <p className="inspector-note">可以编辑和保存程序；代码执行服务尚未开放，暂不能自动核验此目标。</p>}<Link className="button primary" to={`/learn/${selected}`}>{selected === TRACE_OBJECTIVE ? '进入推演工作台' : '打开实现工作台'}<span aria-hidden="true">↗</span></Link><Link className="text-link" to="/evidence">查看已有作品与核验 →</Link></aside></section>
      <section className="objective-list" aria-labelledby="objective-list-title"><div className="section-heading"><div><div className="eyebrow">同一图谱 · 文字视图</div><h2 id="objective-list-title">两个目标，一条可继续的路径。</h2></div><span className="version-label">{COURSE_VERSION}</span></div>{[{ id: TRACE_OBJECTIVE, title: '推演栈状态与边界', description: '七步操作、后进先出解释、空栈情况', state }, { id: IMPLEMENT_OBJECTIVE, title: '实现括号匹配方法', description: '先修：栈状态推演 · 执行环境待开放', state: 'unknown' as const }].map((objective, index) => <div className="objective-row" key={objective.id}><button className="objective-select" onClick={() => { setSelected(objective.id); document.querySelector('.objective-inspector')?.scrollIntoView({ behavior: matchMedia('(prefers-reduced-motion: reduce)').matches ? 'instant' : 'smooth', block: 'center' }) }}><span className="course-number">0{index + 1}</span><span><strong>{objective.title}</strong><small>{objective.description}</small></span></button><span className={`evidence-pill ${objective.state}`}>{stateLabels[objective.state]}</span><Link className="text-link" to={`/learn/${objective.id}`}>进入 <span aria-hidden="true">↗</span></Link></div>)}</section>
    </>}
  </div>
}
